<a href="https://colab.research.google.com/github/ShrutiPatel263/AeroCare/blob/main/FD001_AllFeatures_WeightedResults_Done.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

=== Cross-Validation Summary ===

MAE: 9.9078,

 RMSE: 13.3048,

  R²: 0.8945

Best Fold: 3

✅ Weighted Ensemble Test Results:

  MAE:  10.7311

  RMSE: 14.6268
  
  R²:   0.8726

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Pre-processing

In [ ]:
import numpy as np
import pandas as pd

from IPython.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', -1)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

# configure plotly graph objects
pio.renderers.default = 'iframe'
# pio.renderers.default = 'vscode'

pio.templates["ck_template"] = go.layout.Template(
    layout_colorway = px.colors.sequential.Viridis,
#     layout_hovermode = 'closest',
#     layout_hoverdistance = -1,
    layout_autosize=False,
    layout_width=800,
    layout_height=600,
    layout_font = dict(family="Calibri Light"),
    layout_title_font = dict(family="Calibri"),
    layout_hoverlabel_font = dict(family="Calibri Light"),
#     plot_bgcolor="white",
)

# pio.templates.default = 'seaborn+ck_template+gridon'
pio.templates.default = 'ck_template+gridon'
# pio.templates.default = 'seaborn+gridon'
# pio.templates

In [ ]:
index_names = ['engine', 'cycle']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names=[ "(Fan inlet temperature) (◦R)",
"(LPC outlet temperature) (◦R)",
"(HPC outlet temperature) (◦R)",
"(LPT outlet temperature) (◦R)",
"(Fan inlet Pressure) (psia)",
"(bypass-duct pressure) (psia)",
"(HPC outlet pressure) (psia)",
"(Physical fan speed) (rpm)",
"(Physical core speed) (rpm)",
"(Engine pressure ratio(P50/P2)",
"(HPC outlet Static pressure) (psia)",
"(Ratio of fuel flow to Ps30) (pps/psia)",
"(Corrected fan speed) (rpm)",
"(Corrected core speed) (rpm)",
"(Bypass Ratio) ",
"(Burner fuel-air ratio)",
"(Bleed Enthalpy)",
"(Required fan speed)",
"(Required fan conversion speed)",
"(High-pressure turbines Cool air flow)",
"(Low-pressure turbines Cool air flow)" ]
col_names = index_names + setting_names + sensor_names

In [ ]:
df_train = pd.read_csv('drive/MyDrive/CMaps/train_FD001.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test = pd.read_csv('drive/MyDrive/CMaps/test_FD001.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test_RUL = pd.read_csv('drive/MyDrive/CMaps/RUL_FD001.txt',sep=r'\s+',header=None,index_col=False,names=['RUL'])

In [ ]:
keep_features = [
    "(Fan inlet temperature) (◦R)",
    "(LPC outlet temperature) (◦R)",
    "(HPC outlet temperature) (◦R)",
    "(LPT outlet temperature) (◦R)",
    "(Fan inlet Pressure) (psia)",
    "(bypass-duct pressure) (psia)",
    "(HPC outlet pressure) (psia)",
    "(Physical fan speed) (rpm)",
    "(Physical core speed) (rpm)",
    "(Engine pressure ratio(P50/P2)",
    "(HPC outlet Static pressure) (psia)",
    "(Ratio of fuel flow to Ps30) (pps/psia)",
    "(Corrected fan speed) (rpm)",
    "(Corrected core speed) (rpm)",
    "(Bypass Ratio) ",
    "(Burner fuel-air ratio)",
    "(Bleed Enthalpy)",
    "(Required fan speed)",
    "(Required fan conversion speed)",
    "(High-pressure turbines Cool air flow)",
    "(Low-pressure turbines Cool air flow)",
    "setting_1",
    "setting_2",
    "setting_3"
]

In [ ]:
features = list(keep_features)

In [ ]:
# define the maximum life of each engine, as this could be used to obtain the RUL at each point in time of the engine's life
df_train_RUL = df_train.groupby(['engine']).agg({'cycle':'max'})
df_train_RUL.rename(columns={'cycle':'life'},inplace=True)
df_train_RUL.head()

        life
engine
1        192
2        287
3        179
4        189
5        269

In [ ]:
df_train=df_train.merge(df_train_RUL,how='left',on=['engine'])

In [ ]:
df_train['RUL']=df_train['life']-df_train['cycle']
df_train.drop(['life'],axis=1,inplace=True)

# the RUL prediction is only useful nearer to the end of the engine's life, therefore we put an upper limit on the RUL
# this is a bit sneaky, since it supposes that the test set has RULs of less than this value, the closer you are
# to the true value, the more accurate the model will be
df_train['RUL'][df_train['RUL']>125]=125
df_train.head()

   engine  cycle  setting_1  setting_2  setting_3  (Fan inlet temperature) (◦R)  (LPC outlet temperature) (◦R)  (HPC outlet temperature) (◦R)  (LPT outlet temperature) (◦R)  (Fan inlet Pressure) (psia)  (bypass-duct pressure) (psia)  (HPC outlet pressure) (psia)  (Physical fan speed) (rpm)  (Physical core speed) (rpm)  (Engine pressure ratio(P50/P2)  (HPC outlet Static pressure) (psia)  (Ratio of fuel flow to Ps30) (pps/psia)  (Corrected fan speed) (rpm)  (Corrected core speed) (rpm)  (Bypass Ratio)   (Burner fuel-air ratio)  (Bleed Enthalpy)  (Required fan speed)  (Required fan conversion speed)  (High-pressure turbines Cool air flow)  (Low-pressure turbines Cool air flow)  RUL
0       1      1    -0.0007    -0.0004      100.0                        518.67                         641.82                        1589.70                        1400.60                        14.62                          21.61                        554.36                     2388.06                      9046.19                             1.3                                47.47                                   521.66                      2388.02                       8138.62           8.4195                     0.03               392                  2388                            100.0                                   39.06                                23.4190  125
1       1      2     0.0019    -0.0003      100.0                        518.67                         642.15                        1591.82                        1403.14                        14.62                          21.61                        553.75                     2388.04                      9044.07                             1.3                                47.49                                   522.28                      2388.07                       8131.49           8.4318                     0.03               392                  2388                            100.0                                   39.00                                23.4236  125
2       1      3    -0.0043     0.0003      100.0                        518.67                         642.35                        1587.99                        1404.20                        14.62                          21.61                        554.26                     2388.08                      9052.94                             1.3                                47.27                                   522.42                      2388.03                       8133.23           8.4178                     0.03               390                  2388                            100.0                                   38.95                                23.3442  125
3       1      4     0.0007     0.0000      100.0                        518.67                         642.35                        1582.79                        1401.87                        14.62                          21.61                        554.45                     2388.11                      9049.48                             1.3                                47.13                                   522.86                      2388.08                       8133.83           8.3682                     0.03               392                  2388                            100.0                                   38.88                                23.3739  125
4       1      5    -0.0019    -0.0002      100.0                        518.67                         642.37                        1582.85                        1406.22                        14.62                          21.61                        554.00                     2388.06                      9055.15                             1.3                                47.28                                   522.19                      2388.04                       8133.80           8.4294                     0.03               393                  2388                            100.0                                   38.90                                23.4044  125

In [ ]:
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values
        rul_values = engine_data['RUL'].values

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)



# Scale features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
feature_cols = [col for col in df_train.columns if col not in ['engine', 'cycle', 'RUL']]
df_train[feature_cols] = scaler.fit_transform(df_train[feature_cols])
df_test[feature_cols] = scaler.transform(df_test[feature_cols])

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
# ============================================================
# ADVANCED RUL PREDICTION: Gated Ensemble BiLSTM + Attention (Optimized)
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers, callbacks, optimizers
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# MODIFIED create_sequences function to handle missing 'RUL' column for test set
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    # Check if 'RUL' column exists in the DataFrame
    has_rul = 'RUL' in df.columns

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values

        if has_rul:
            rul_values = engine_data['RUL'].values
        else:
            # If RUL column is not present (e.g., for test data), create a dummy array.
            # These 'targets' will be discarded for X_test anyway.
            rul_values = np.array([])

        # Ensure there are enough data points for the window
        if len(values) < window_size:
            continue # Skip engines that are too short for a single sequence

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            if has_rul: # Only append RUL target if RUL column exists
                targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)


CONFIG = {
    'WINDOW_SIZE': 60,        # FD001 engines avg ~200 cycles; 30 is sharper
    'STRIDE': 1,
    'LSTM_UNITS': [128, 64],
    'DENSE_UNITS': 80,
    'DROPOUT_RATE': 0.2,      # Reduced — your CV→test gap suggests mild overfit
    'L2_REG': 0.0005,         # Slightly relaxed
    'BATCH_SIZE': 32,         # Smaller batch → better generalization
    'EPOCHS': 200,
    'LEARNING_RATE': 0.001,
    'PATIENCE': 20,           # Tighter early stopping
    'N_SPLITS': 5
}

print("\nOptimized Configuration:")
for k, v in CONFIG.items():
    print(f"  {k}: {v}")


X_train, y_train, train_engine_ids = create_sequences(
    df_train, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)
X_test, _, test_engine_ids = create_sequences(
    df_test, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)

print(f"Training sequences: {X_train.shape}")
print(f"Test sequences: {X_test.shape}")


# ============================================================
# Custom Layers
# ============================================================

class GatingLayer(layers.Layer):
    def __init__(self, num_branches, **kwargs):
        super(GatingLayer, self).__init__(**kwargs)
        self.num_branches = num_branches

    def build(self, input_shape):
        self.gate_weights = self.add_weight(
            shape=(input_shape[0][-1], self.num_branches),
            initializer='glorot_uniform',
            trainable=True
        )
        self.gate_bias = self.add_weight(
            shape=(self.num_branches,),
            initializer='zeros',
            trainable=True
        )

    def call(self, inputs):
        input_stats = tf.reduce_mean(inputs[0], axis=1)
        gate_scores = tf.nn.softmax(tf.matmul(input_stats, self.gate_weights) + self.gate_bias, axis=-1)
        gate_scores = tf.expand_dims(tf.expand_dims(gate_scores, 1), -1)
        stacked = tf.stack(inputs, axis=2)
        gated = stacked * gate_scores
        fused = tf.reduce_sum(gated, axis=2)
        return fused


class AttentionLayer(layers.Layer):
    """Attention mechanism to highlight critical timesteps after fusion."""
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1]),
                                 initializer="glorot_uniform", trainable=True)
        self.b = self.add_weight(shape=(input_shape[-1],),
                                 initializer="zeros", trainable=True)
        self.u = self.add_weight(shape=(input_shape[-1],),
                                 initializer="glorot_uniform", trainable=True)

    def call(self, x):
        u_t = tf.tanh(tf.tensordot(x, self.W, axes=1) + self.b)
        attn_scores = tf.nn.softmax(tf.tensordot(u_t, self.u, axes=1), axis=1)
        attn_scores = tf.expand_dims(attn_scores, -1)
        context = tf.reduce_sum(x * attn_scores, axis=1)
        return context


# ============================================================
# Optimized Gated BiLSTM + Attention Model
# ============================================================

def build_gated_attention_bilstm(input_shape, config):
    inputs = layers.Input(shape=input_shape, name='input')

    # Parallel branches: LSTM, GRU, CNN
    branch_lstm = layers.LSTM(64, return_sequences=True,
                              kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_lstm = layers.LayerNormalization()(branch_lstm)

    branch_gru = layers.GRU(64, return_sequences=True,
                            kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_gru = layers.LayerNormalization()(branch_gru)

    branch_cnn = layers.Conv1D(64, 5, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_cnn = layers.Conv1D(64, 3, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(branch_cnn)
    branch_cnn = layers.LayerNormalization()(branch_cnn)

    fused = GatingLayer(num_branches=3)([branch_lstm, branch_gru, branch_cnn])
    fused = layers.Dropout(config['DROPOUT_RATE'])(fused)

    # BiLSTM layers for sequential modeling
    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][0],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_1'
    )(fused)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][1],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_2'
    )(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    # Attention layer
    context = AttentionLayer()(x)

    # Dense head
    x = layers.Dense(config['DENSE_UNITS'], activation='relu')(context)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    outputs = layers.Dense(1, activation='linear', name='rul_output')(x)

    model = models.Model(inputs, outputs, name='Gated_Attention_BiLSTM')

    opt = optimizers.Adam(learning_rate=config['LEARNING_RATE'])
    model.compile(
        optimizer=opt,
        loss=tf.keras.losses.Huber(delta=12.0),
        metrics=['mae', 'mse']
    )
    return model


# ============================================================
# Train with Advanced Callbacks
# ============================================================

# ============================================================
# Train with Advanced Callbacks
# ============================================================

def train_model_with_cv(X_train, y_train, engine_ids, input_shape, config, n_splits=5):
    from sklearn.model_selection import GroupKFold

    gkf = GroupKFold(n_splits=n_splits)
    results, models_list = [], []

    for fold, (tr_idx, val_idx) in enumerate(gkf.split(X_train, y_train, engine_ids), 1):
        print(f"\n{'='*25} FOLD {fold}/{n_splits} {'='*25}")
        X_tr, X_val = X_train[tr_idx], X_train[val_idx]
        y_tr, y_val = y_train[tr_idx], y_train[val_idx]

        model = build_gated_attention_bilstm(input_shape, config)

        cb = [
            callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.4, patience=6, min_lr=5e-6),
            callbacks.EarlyStopping(monitor='val_loss', patience=config['PATIENCE'],
                                    restore_best_weights=True),
            callbacks.ModelCheckpoint(f"best_fold_{fold}.h5", save_best_only=True)
        ]

        history = model.fit(
            X_tr, y_tr,
            validation_data=(X_val, y_val),
            epochs=config['EPOCHS'],
            batch_size=config['BATCH_SIZE'],
            verbose=1,
            callbacks=cb
        )

        val_loss, val_mae, val_mse = model.evaluate(X_val, y_val, verbose=0)
        val_rmse = np.sqrt(val_mse)

        y_pred_val = model.predict(X_val, verbose=0).flatten()
        val_r2 = r2_score(y_val, y_pred_val)

        results.append({'fold': fold, 'mae': val_mae, 'rmse': val_rmse, 'r2': val_r2})
        models_list.append(model)

        print(f"Fold {fold} Results -> MAE: {val_mae:.4f}, RMSE: {val_rmse:.4f}, R²: {val_r2:.4f}")

    print("\n=== Cross-Validation Summary ===")
    avg_mae  = np.mean([r['mae']  for r in results])
    avg_rmse = np.mean([r['rmse'] for r in results])
    avg_r2   = np.mean([r['r2']   for r in results])
    print(f"MAE: {avg_mae:.4f}, RMSE: {avg_rmse:.4f}, R²: {avg_r2:.4f}")

    best_model_idx = np.argmax([r['r2'] for r in results])
    print(f"\nBest Fold: {best_model_idx + 1}")

    return models_list, results   # ← returns ALL models now


# ============================================================
# Execute Training
# ============================================================

input_shape = (X_train.shape[1], X_train.shape[2])
all_models, cv_results = train_model_with_cv(
    X_train, y_train, train_engine_ids, input_shape, CONFIG, CONFIG['N_SPLITS']
)

# ============================================================
# Ensemble ALL folds for test prediction
# ============================================================

# ============================================================
# Weighted Ensemble by fold R² score
# ============================================================

fold_r2_scores = np.array([r['r2'] for r in cv_results])
fold_weights = fold_r2_scores / fold_r2_scores.sum()  # normalize to sum=1

print("\nFold weights:")
for i, (r2, w) in enumerate(zip(fold_r2_scores, fold_weights), 1):
    print(f"  Fold {i}: R²={r2:.4f}, weight={w:.4f}")

all_preds = []
for m in all_models:
    preds = m.predict(X_test, verbose=0).flatten()
    preds = np.clip(preds, 0, None)
    all_preds.append(preds)

# Weighted average
y_test_pred_all = np.average(all_preds, axis=0, weights=fold_weights)

unique_engines = sorted(set(test_engine_ids))
y_true, y_pred = [], []
for eng_id in unique_engines:
    mask = test_engine_ids == eng_id
    y_pred.append(y_test_pred_all[mask][-1])
    y_true.append(df_test_RUL.iloc[int(eng_id) - 1]['RUL'])

y_true, y_pred = np.array(y_true), np.array(y_pred)
test_mae  = mean_absolute_error(y_true, y_pred)
test_rmse = np.sqrt(mean_squared_error(y_true, y_pred))
test_r2   = r2_score(y_true, y_pred)

print(f"\n✅ Weighted Ensemble Test Results:")
print(f"  MAE:  {test_mae:.4f}")
print(f"  RMSE: {test_rmse:.4f}")
print(f"  R²:   {test_r2:.4f}")

if test_r2 >= 0.88:
    print("\n🏆 EXCELLENT PERFORMANCE ACHIEVED!")

Optimized Configuration:
  WINDOW_SIZE: 60
  STRIDE: 1
  LSTM_UNITS: [128, 64]
  DENSE_UNITS: 80
  DROPOUT_RATE: 0.2
  L2_REG: 0.0005
  BATCH_SIZE: 32
  EPOCHS: 200
  LEARNING_RATE: 0.001
  PATIENCE: 20
  N_SPLITS: 5
Training sequences: (14731, 60, 24)
Test sequences: (7351, 60, 24)

========================= FOLD 1/5 =========================
Epoch 1/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 294.5132 - mae: 29.6918 - mse: 1812.3927

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 37s 39ms/step - loss: 294.1395 - mae: 29.6596 - mse: 1809.4819 - val_loss: 86.8262 - val_mae: 12.1867 - val_mse: 223.1312 - learning_rate: 0.0010
Epoch 2/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 59.8931 - mae: 9.0814 - mse: 156.4298

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 59.8847 - mae: 9.0806 - mse: 156.4006 - val_loss: 71.8341 - val_mae: 10.4788 - val_mse: 185.8433 - learning_rate: 0.0010
Epoch 3/200
368/369 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 46.3616 - mae: 7.7300 - mse: 112.8492

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 46.3546 - mae: 7.7292 - mse: 112.8280 - val_loss: 69.6046 - val_mae: 10.3767 - val_mse: 168.2966 - learning_rate: 0.0010
Epoch 4/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 37.4609 - mae: 6.7267 - mse: 86.7429 - val_loss: 77.7675 - val_mae: 11.1582 - val_mse: 196.6268 - learning_rate: 0.0010
Epoch 5/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 33.8654 - mae: 6.3753 - mse: 76.4472 - val_loss: 83.6979 - val_mae: 11.5154 - val_mse: 217.1730 - learning_rate: 0.0010
Epoch 6/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 32.7587 - mae: 6.1719 - mse: 73.5698 - val_loss: 79.6739 - val_mae: 11.0659 - val_mse: 205.7100 - learning_rate: 0.0010
Epoch 7/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 29.9061 - mae: 5.8668 - mse: 65.2434 - val_loss: 82.8197 - val_mae: 11.0168 - val_mse: 221.5796 - learning_rate: 0.0010
Epoch 8/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 27.9883 - mae: 5.6305 - mse: 60.9759 - val_loss: 88.4006 - val_mae: 11.6293 - val_mse: 241.7881 - learning_rate: 0.0010
Epoch 9/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 28.5085 - mae: 5.7045 - mse: 62.4432 - val_loss: 89.2602 - val_mae: 11.9596 - val_mse: 249.2173 - learning_rate: 0.0010
Epoch 10/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 27.2333 - mae: 5.4831 - mse: 58.6233 - val_loss: 85.9717 - val_mae: 11.6646 - val_mse: 228.6610 - learning_rate: 4.0000e-04
Epoch 11/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 23.5696 - mae: 5.0041 - mse: 50.5068 - val_loss: 86.3702 - val_mae: 11.6952 - val_mse: 229.5285 - learning_rate: 4.0000e-04
Epoch 12/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 23.2899 - mae: 4.9660 - mse: 49.2714 - val_loss: 88.4958 - val_mae: 11.7507 - val_mse: 235.4632 - learning_rate: 4.0000e-04
Epoch 13/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 23.6280 - mae: 5.0084 - mse: 50.0485 - val_loss: 85.1501 - val_mae: 11.5557 - val_mse: 224.0182 - learning_rate: 4.0000e-04
Epoch 14/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - loss: 22.6513 - mae: 4.9141 - mse: 48.2185 - val_loss: 88.6197 - val_mae: 11.9304 - val_mse: 235.0581 - learning_rate: 4.0000e-04
Epoch 15/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 23.3941 - mae: 5.0144 - mse: 49.4619 - val_loss: 93.1371 - val_mae: 12.0016 - val_mse: 261.5977 - learning_rate: 4.0000e-04
Epoch 16/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 22.1300 - mae: 4.8056 - mse: 46.4537 - val_loss: 89.0641 - val_mae: 11.8182 - val_mse: 235.9587 - learning_rate: 1.6000e-04
Epoch 17/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 22.0067 - mae: 4.8005 - mse: 46.3461 - val_loss: 88.2942 - val_mae: 11.7384 - val_mse: 235.9597 - learning_rate: 1.6000e-04
Epoch 18/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 22.5627 - mae: 4.8113 - mse: 47.8235 - val_loss: 87.2309 - val_mae: 11.7545 - val_mse: 231.2841 - learning_rate: 1.6000e-04
Epoch 19/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.5087 - mae: 4.7206 - mse: 45.2326 - val_loss: 95.2489 - val_mae: 12.4262 - val_mse: 262.4347 - learning_rate: 1.6000e-04
Epoch 20/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.9019 - mae: 4.7452 - mse: 46.0230 - val_loss: 88.9816 - val_mae: 11.8726 - val_mse: 235.7513 - learning_rate: 1.6000e-04
Epoch 21/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.7016 - mae: 4.7839 - mse: 44.7861 - val_loss: 89.4198 - val_mae: 11.7610 - val_mse: 241.8831 - learning_rate: 1.6000e-04
Epoch 22/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 21.2615 - mae: 4.6864 - mse: 44.3331 - val_loss: 87.4593 - val_mae: 11.7297 - val_mse: 230.3625 - learning_rate: 6.4000e-05
Epoch 23/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.3458 - mae: 4.6693 - mse: 44.9404 - val_loss: 88.2784 - val_mae: 11.8881 - val_mse: 231.2728 - learning_rate: 6.4000e-05
Fold 1 Results -> MAE: 10.3767, RMSE: 12.9729, R²: 0.9002

========================= FOLD 2/5 =========================
Epoch 1/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 293.9714 - mae: 29.6313 - mse: 1805.7142

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 23s 38ms/step - loss: 293.5998 - mae: 29.5993 - mse: 1802.8191 - val_loss: 89.3538 - val_mae: 12.0514 - val_mse: 260.5735 - learning_rate: 0.0010
Epoch 2/200
368/369 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 70.1410 - mae: 10.1194 - mse: 188.2132

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 70.1084 - mae: 10.1162 - mse: 188.1149 - val_loss: 66.9019 - val_mae: 9.7487 - val_mse: 173.8226 - learning_rate: 0.0010
Epoch 3/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 51.1248 - mae: 8.2275 - mse: 127.0063 - val_loss: 96.7672 - val_mae: 12.7501 - val_mse: 276.7964 - learning_rate: 0.0010
Epoch 4/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 42.2714 - mae: 7.3704 - mse: 97.4766 - val_loss: 77.9387 - val_mae: 10.8761 - val_mse: 219.2320 - learning_rate: 0.0010
Epoch 5/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 32.8612 - mae: 6.3302 - mse: 73.3456 - val_loss: 74.2915 - val_mae: 10.3831 - val_mse: 201.1610 - learning_rate: 0.0010
Epoch 6/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 28.7708 - mae: 5.7888 - mse: 62.8070 - val_loss: 77.1402 - val_mae: 10.5375 - val_mse: 216.6989 - learning_rate: 0.0010
Epoch 7/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 30.7958 - mae: 6.0440 - mse: 67.1279 - val_loss: 86.5057 - val_mae: 11.3262 - val_mse: 249.7558 - learning_rate: 0.0010
Epoch 8/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 27.6335 - mae: 5.6664 - mse: 59.3508 - val_loss: 70.7790 - val_mae: 9.5507 - val_mse: 213.3958 - learning_rate: 0.0010
Epoch 9/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - loss: 21.8743 - mae: 4.9170 - mse: 45.0894 - val_loss: 78.2503 - val_mae: 10.5073 - val_mse: 221.8392 - learning_rate: 4.0000e-04
Epoch 10/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 20.9588 - mae: 4.7612 - mse: 43.4808 - val_loss: 77.2616 - val_mae: 10.3707 - val_mse: 220.3676 - learning_rate: 4.0000e-04
Epoch 11/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 20.7589 - mae: 4.7499 - mse: 42.6946 - val_loss: 78.6620 - val_mae: 10.5048 - val_mse: 231.4309 - learning_rate: 4.0000e-04
Epoch 12/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 19.8081 - mae: 4.6574 - mse: 40.3498 - val_loss: 77.5355 - val_mae: 10.4351 - val_mse: 224.7657 - learning_rate: 4.0000e-04
Epoch 13/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 19.9923 - mae: 4.6547 - mse: 41.0665 - val_loss: 82.9872 - val_mae: 10.9027 - val_mse: 242.7857 - learning_rate: 4.0000e-04
Epoch 14/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 20.2339 - mae: 4.6563 - mse: 41.6300 - val_loss: 79.4479 - val_mae: 10.4365 - val_mse: 237.7120 - learning_rate: 4.0000e-04
Epoch 15/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 19.1971 - mae: 4.5323 - mse: 39.3592 - val_loss: 78.8541 - val_mae: 10.4590 - val_mse: 227.1158 - learning_rate: 1.6000e-04
Epoch 16/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 19.2501 - mae: 4.4903 - mse: 39.6510 - val_loss: 81.6364 - val_mae: 10.6974 - val_mse: 238.6805 - learning_rate: 1.6000e-04
Epoch 17/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 18.8005 - mae: 4.4303 - mse: 38.3846 - val_loss: 86.5934 - val_mae: 11.0144 - val_mse: 260.1351 - learning_rate: 1.6000e-04
Epoch 18/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 18.6617 - mae: 4.4313 - mse: 37.8965 - val_loss: 82.4430 - val_mae: 10.7398 - val_mse: 241.1730 - learning_rate: 1.6000e-04
Epoch 19/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 18.9506 - mae: 4.4636 - mse: 38.7824 - val_loss: 84.4052 - val_mae: 10.8392 - val_mse: 253.5638 - learning_rate: 1.6000e-04
Epoch 20/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 18.2734 - mae: 4.3742 - mse: 37.1075 - val_loss: 84.9337 - val_mae: 10.9104 - val_mse: 254.0080 - learning_rate: 1.6000e-04
Epoch 21/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 18.8320 - mae: 4.4067 - mse: 38.7343 - val_loss: 85.2518 - val_mae: 10.9458 - val_mse: 254.8716 - learning_rate: 6.4000e-05
Epoch 22/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 18.7423 - mae: 4.3917 - mse: 38.0357 - val_loss: 86.3197 - val_mae: 11.0162 - val_mse: 260.5635 - learning_rate: 6.4000e-05
Fold 2 Results -> MAE: 9.7487, RMSE: 13.1842, R²: 0.8964

========================= FOLD 3/5 =========================
Epoch 1/200
368/369 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 333.3043 - mae: 32.9922 - mse: 2139.5020

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 24s 40ms/step - loss: 332.4466 - mae: 32.9184 - mse: 2132.6267 - val_loss: 100.0808 - val_mae: 13.1180 - val_mse: 311.1256 - learning_rate: 0.0010
Epoch 2/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 71.0139 - mae: 10.2686 - mse: 188.6745

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 70.9960 - mae: 10.2667 - mse: 188.6189 - val_loss: 65.8858 - val_mae: 9.8793 - val_mse: 169.4412 - learning_rate: 0.0010
Epoch 3/200
368/369 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 50.8612 - mae: 8.2159 - mse: 124.6779

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 50.8417 - mae: 8.2137 - mse: 124.6264 - val_loss: 61.4636 - val_mae: 9.1468 - val_mse: 158.0043 - learning_rate: 0.0010
Epoch 4/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 42.0032 - mae: 7.2698 - mse: 98.6887 - val_loss: 66.2599 - val_mae: 9.4755 - val_mse: 175.1023 - learning_rate: 0.0010
Epoch 5/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 37.4276 - mae: 6.8167 - mse: 85.8000 - val_loss: 62.2263 - val_mae: 9.3342 - val_mse: 157.6391 - learning_rate: 0.0010
Epoch 6/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 32.0851 - mae: 6.1819 - mse: 71.1599

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 32.0824 - mae: 6.1816 - mse: 71.1519 - val_loss: 60.1037 - val_mae: 8.8426 - val_mse: 151.2490 - learning_rate: 0.0010
Epoch 7/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 29.2835 - mae: 5.8455 - mse: 63.7542 - val_loss: 71.4455 - val_mae: 9.9512 - val_mse: 191.0167 - learning_rate: 0.0010
Epoch 8/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 27.2307 - mae: 5.6499 - mse: 57.8427 - val_loss: 67.1658 - val_mae: 9.7754 - val_mse: 173.0617 - learning_rate: 0.0010
Epoch 9/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 25.5724 - mae: 5.3826 - mse: 54.0765 - val_loss: 72.8681 - val_mae: 10.0683 - val_mse: 198.8159 - learning_rate: 0.0010
Epoch 10/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 25.2785 - mae: 5.3640 - mse: 52.8664 - val_loss: 75.6449 - val_mae: 10.2413 - val_mse: 213.1057 - learning_rate: 0.0010
Epoch 11/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 25.9020 - mae: 5.4633 - mse: 54.5364 - val_loss: 70.4257 - val_mae: 9.9082 - val_mse: 193.8720 - learning_rate: 0.0010
Epoch 12/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 24.2929 - mae: 5.2055 - mse: 51.1994 - val_loss: 74.5102 - val_mae: 10.3784 - val_mse: 204.3100 - learning_rate: 0.0010
Epoch 13/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 22.7803 - mae: 4.9724 - mse: 47.4228 - val_loss: 77.9904 - val_mae: 10.7171 - val_mse: 217.9541 - learning_rate: 4.0000e-04
Epoch 14/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 21.8426 - mae: 4.8219 - mse: 45.1515 - val_loss: 68.1231 - val_mae: 9.6025 - val_mse: 182.6895 - learning_rate: 4.0000e-04
Epoch 15/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - loss: 21.7170 - mae: 4.8285 - mse: 44.9684 - val_loss: 72.5920 - val_mae: 10.0276 - val_mse: 204.5134 - learning_rate: 4.0000e-04
Epoch 16/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 20.6902 - mae: 4.6913 - mse: 42.8342 - val_loss: 75.5050 - val_mae: 10.2996 - val_mse: 208.4920 - learning_rate: 4.0000e-04
Epoch 17/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - loss: 20.7953 - mae: 4.7189 - mse: 42.6635 - val_loss: 75.3653 - val_mae: 10.3212 - val_mse: 215.4861 - learning_rate: 4.0000e-04
Epoch 18/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 21.6522 - mae: 4.7781 - mse: 44.9525 - val_loss: 67.5709 - val_mae: 9.7787 - val_mse: 182.2173 - learning_rate: 4.0000e-04
Epoch 19/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 20.1848 - mae: 4.5925 - mse: 41.6207 - val_loss: 71.1146 - val_mae: 10.0239 - val_mse: 191.9596 - learning_rate: 1.6000e-04
Epoch 20/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 20.6249 - mae: 4.6248 - mse: 42.8712 - val_loss: 69.6087 - val_mae: 9.9605 - val_mse: 186.8419 - learning_rate: 1.6000e-04
Epoch 21/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 20.8146 - mae: 4.6395 - mse: 43.0390 - val_loss: 70.1309 - val_mae: 9.8573 - val_mse: 191.9995 - learning_rate: 1.6000e-04
Epoch 22/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 20.3470 - mae: 4.5808 - mse: 42.0105 - val_loss: 76.4293 - val_mae: 10.4080 - val_mse: 215.3642 - learning_rate: 1.6000e-04
Epoch 23/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 20.2972 - mae: 4.5779 - mse: 41.7625 - val_loss: 68.9540 - val_mae: 9.8471 - val_mse: 185.3023 - learning_rate: 1.6000e-04
Epoch 24/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 20.5710 - mae: 4.6396 - mse: 42.7593 - val_loss: 76.2300 - val_mae: 10.4702 - val_mse: 215.4542 - learning_rate: 1.6000e-04
Epoch 25/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 20.0798 - mae: 4.5620 - mse: 41.2695 - val_loss: 73.5302 - val_mae: 10.1970 - val_mse: 204.1021 - learning_rate: 6.4000e-05
Epoch 26/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 19.5247 - mae: 4.4615 - mse: 40.1086 - val_loss: 75.6523 - val_mae: 10.3635 - val_mse: 216.2752 - learning_rate: 6.4000e-05
Fold 3 Results -> MAE: 8.8426, RMSE: 12.2983, R²: 0.9101

========================= FOLD 4/5 =========================
Epoch 1/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 329.4473 - mae: 32.6706 - mse: 2093.7407

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 22s 36ms/step - loss: 329.0374 - mae: 32.6355 - mse: 2090.4707 - val_loss: 81.6718 - val_mae: 10.9489 - val_mse: 239.6705 - learning_rate: 0.0010
Epoch 2/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 72.8151 - mae: 10.3627 - mse: 202.9154

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - loss: 72.7943 - mae: 10.3607 - mse: 202.8345 - val_loss: 70.6366 - val_mae: 10.1638 - val_mse: 199.1574 - learning_rate: 0.0010
Epoch 3/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 50.8253 - mae: 8.2309 - mse: 125.7379 - val_loss: 73.4354 - val_mae: 10.3999 - val_mse: 213.8666 - learning_rate: 0.0010
Epoch 4/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 42.3108 - mae: 7.2850 - mse: 99.5162 - val_loss: 72.8495 - val_mae: 10.3937 - val_mse: 211.1155 - learning_rate: 0.0010
Epoch 5/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 34.7342 - mae: 6.4810 - mse: 78.5357 - val_loss: 80.2328 - val_mae: 11.1929 - val_mse: 228.5033 - learning_rate: 0.0010
Epoch 6/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 32.9517 - mae: 6.3019 - mse: 72.6562 - val_loss: 83.4885 - val_mae: 11.3114 - val_mse: 257.4086 - learning_rate: 0.0010
Epoch 7/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 29.8737 - mae: 5.9221 - mse: 64.9949 - val_loss: 85.0687 - val_mae: 11.4592 - val_mse: 255.3825 - learning_rate: 0.0010
Epoch 8/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 27.8554 - mae: 5.6259 - mse: 60.2577 - val_loss: 94.6044 - val_mae: 12.2057 - val_mse: 287.5043 - learning_rate: 0.0010
Epoch 9/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 25.5306 - mae: 5.2917 - mse: 54.8642 - val_loss: 95.6035 - val_mae: 12.2221 - val_mse: 298.8079 - learning_rate: 4.0000e-04
Epoch 10/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 24.2258 - mae: 5.1835 - mse: 51.0362 - val_loss: 84.2250 - val_mae: 11.1666 - val_mse: 251.8335 - learning_rate: 4.0000e-04
Epoch 11/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 22.8533 - mae: 4.9457 - mse: 48.2400 - val_loss: 86.4253 - val_mae: 11.3384 - val_mse: 264.2290 - learning_rate: 4.0000e-04
Epoch 12/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 22.9923 - mae: 4.9874 - mse: 48.0500 - val_loss: 89.2197 - val_mae: 11.7279 - val_mse: 265.0271 - learning_rate: 4.0000e-04
Epoch 13/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 23.1987 - mae: 5.0097 - mse: 49.1705 - val_loss: 91.1155 - val_mae: 12.0216 - val_mse: 271.3792 - learning_rate: 4.0000e-04
Epoch 14/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 22.4272 - mae: 4.9260 - mse: 46.6709 - val_loss: 86.8383 - val_mae: 11.4189 - val_mse: 269.7973 - learning_rate: 4.0000e-04
Epoch 15/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 22.2858 - mae: 4.8769 - mse: 46.4113 - val_loss: 96.8611 - val_mae: 12.3411 - val_mse: 300.7979 - learning_rate: 1.6000e-04
Epoch 16/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 21.5326 - mae: 4.7722 - mse: 44.8447 - val_loss: 96.5340 - val_mae: 12.4602 - val_mse: 294.7061 - learning_rate: 1.6000e-04
Epoch 17/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 21.0931 - mae: 4.7336 - mse: 43.8533 - val_loss: 96.8494 - val_mae: 12.2060 - val_mse: 309.5502 - learning_rate: 1.6000e-04
Epoch 18/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - loss: 22.2173 - mae: 4.8744 - mse: 46.3652 - val_loss: 100.3211 - val_mae: 12.4439 - val_mse: 326.6072 - learning_rate: 1.6000e-04
Epoch 19/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.5804 - mae: 4.7716 - mse: 44.5882 - val_loss: 91.4991 - val_mae: 11.7886 - val_mse: 284.6962 - learning_rate: 1.6000e-04
Epoch 20/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.4189 - mae: 4.7591 - mse: 44.7872 - val_loss: 92.3360 - val_mae: 11.8180 - val_mse: 284.2929 - learning_rate: 1.6000e-04
Epoch 21/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 20.7018 - mae: 4.6581 - mse: 42.8651 - val_loss: 90.0312 - val_mae: 11.7175 - val_mse: 278.8347 - learning_rate: 6.4000e-05
Epoch 22/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 20.6806 - mae: 4.6460 - mse: 42.9268 - val_loss: 93.1429 - val_mae: 11.9731 - val_mse: 289.8220 - learning_rate: 6.4000e-05
Fold 4 Results -> MAE: 10.1638, RMSE: 14.1123, R²: 0.8816

========================= FOLD 5/5 =========================
Epoch 1/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 314.8024 - mae: 31.4572 - mse: 1920.0938

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 24s 39ms/step - loss: 314.4337 - mae: 31.4256 - mse: 1917.1799 - val_loss: 93.2810 - val_mae: 12.5211 - val_mse: 266.3472 - learning_rate: 0.0010
Epoch 2/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 86.8281 - mae: 11.6920 - mse: 249.4091

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - loss: 86.8113 - mae: 11.6904 - mse: 249.3505 - val_loss: 77.6704 - val_mae: 11.0688 - val_mse: 203.7243 - learning_rate: 0.0010
Epoch 3/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 59.8174 - mae: 9.0897 - mse: 154.1852

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

369/369 ━━━━━━━━━━━━━━━━━━━━ 19s 35ms/step - loss: 59.8090 - mae: 9.0889 - mse: 154.1572 - val_loss: 71.8253 - val_mae: 10.4071 - val_mse: 194.7818 - learning_rate: 0.0010
Epoch 4/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 45.9776 - mae: 7.6808 - mse: 111.0229 - val_loss: 74.4238 - val_mae: 10.5545 - val_mse: 199.6373 - learning_rate: 0.0010
Epoch 5/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 38.7105 - mae: 6.9658 - mse: 88.3451 - val_loss: 85.7303 - val_mae: 11.6188 - val_mse: 243.9374 - learning_rate: 0.0010
Epoch 6/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 35.0108 - mae: 6.5356 - mse: 77.7989 - val_loss: 86.1004 - val_mae: 11.4902 - val_mse: 259.1507 - learning_rate: 0.0010
Epoch 7/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 32.3148 - mae: 6.2186 - mse: 71.2933 - val_loss: 87.4930 - val_mae: 11.5628 - val_mse: 261.0401 - learning_rate: 0.0010
Epoch 8/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 28.8000 - mae: 5.8380 - mse: 61.5145 - val_loss: 80.0614 - val_mae: 10.8631 - val_mse: 225.9718 - learning_rate: 0.0010
Epoch 9/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 26.7699 - mae: 5.5747 - mse: 56.9012 - val_loss: 83.9425 - val_mae: 11.4396 - val_mse: 247.9460 - learning_rate: 0.0010
Epoch 10/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - loss: 23.7458 - mae: 5.1508 - mse: 49.4579 - val_loss: 79.7111 - val_mae: 10.6884 - val_mse: 228.1266 - learning_rate: 4.0000e-04
Epoch 11/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 23.3809 - mae: 5.0346 - mse: 49.2033 - val_loss: 87.6926 - val_mae: 11.4118 - val_mse: 268.9632 - learning_rate: 4.0000e-04
Epoch 12/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 22.8082 - mae: 5.0011 - mse: 47.5626 - val_loss: 93.6626 - val_mae: 11.9899 - val_mse: 294.1696 - learning_rate: 4.0000e-04
Epoch 13/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 22.5143 - mae: 4.9442 - mse: 47.0620 - val_loss: 83.4652 - val_mae: 11.1747 - val_mse: 241.2795 - learning_rate: 4.0000e-04
Epoch 14/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 22.4972 - mae: 4.9383 - mse: 47.1063 - val_loss: 96.5310 - val_mae: 12.2651 - val_mse: 304.9790 - learning_rate: 4.0000e-04
Epoch 15/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.6995 - mae: 4.8513 - mse: 44.9899 - val_loss: 83.6029 - val_mae: 11.0840 - val_mse: 250.3445 - learning_rate: 4.0000e-04
Epoch 16/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.8146 - mae: 4.8056 - mse: 45.5808 - val_loss: 84.1523 - val_mae: 11.1812 - val_mse: 248.2127 - learning_rate: 1.6000e-04
Epoch 17/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.4764 - mae: 4.7706 - mse: 44.7102 - val_loss: 90.6864 - val_mae: 11.6332 - val_mse: 282.5068 - learning_rate: 1.6000e-04
Epoch 18/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - loss: 21.8439 - mae: 4.8187 - mse: 45.7819 - val_loss: 89.8900 - val_mae: 11.6468 - val_mse: 269.5078 - learning_rate: 1.6000e-04
Epoch 19/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 21.1165 - mae: 4.7505 - mse: 43.7665 - val_loss: 86.5525 - val_mae: 11.4377 - val_mse: 258.4393 - learning_rate: 1.6000e-04
Epoch 20/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 20.5835 - mae: 4.6339 - mse: 42.3553 - val_loss: 87.1698 - val_mae: 11.4761 - val_mse: 258.5494 - learning_rate: 1.6000e-04
Epoch 21/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - loss: 20.5512 - mae: 4.6657 - mse: 42.3284 - val_loss: 94.8777 - val_mae: 12.1021 - val_mse: 291.3766 - learning_rate: 1.6000e-04
Epoch 22/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 20.5511 - mae: 4.6710 - mse: 42.4516 - val_loss: 85.4576 - val_mae: 11.2924 - val_mse: 254.9464 - learning_rate: 6.4000e-05
Epoch 23/200
369/369 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - loss: 20.6090 - mae: 4.6697 - mse: 42.7318 - val_loss: 86.5987 - val_mae: 11.3103 - val_mse: 261.6252 - learning_rate: 6.4000e-05
Fold 5 Results -> MAE: 10.4071, RMSE: 13.9564, R²: 0.8841

=== Cross-Validation Summary ===
MAE: 9.9078, RMSE: 13.3048, R²: 0.8945

Best Fold: 3

Fold weights:
  Fold 1: R²=0.9002, weight=0.2013
  Fold 2: R²=0.8964, weight=0.2004
  Fold 3: R²=0.9101, weight=0.2035
  Fold 4: R²=0.8816, weight=0.1971
  Fold 5: R²=0.8841, weight=0.1977

✅ Weighted Ensemble Test Results:
  MAE:  10.7311
  RMSE: 14.6268
  R²:   0.8726