<a href="https://colab.research.google.com/github/ShrutiPatel263/AeroCare/blob/main/State_of_the_art_FD002_rule_2_60.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Pre-processing

In [ ]:
import numpy as np
import pandas as pd

from IPython.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', -1)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

# configure plotly graph objects
pio.renderers.default = 'iframe'
# pio.renderers.default = 'vscode'

pio.templates["ck_template"] = go.layout.Template(
    layout_colorway = px.colors.sequential.Viridis,
#     layout_hovermode = 'closest',
#     layout_hoverdistance = -1,
    layout_autosize=False,
    layout_width=800,
    layout_height=600,
    layout_font = dict(family="Calibri Light"),
    layout_title_font = dict(family="Calibri"),
    layout_hoverlabel_font = dict(family="Calibri Light"),
#     plot_bgcolor="white",
)

# pio.templates.default = 'seaborn+ck_template+gridon'
pio.templates.default = 'ck_template+gridon'
# pio.templates.default = 'seaborn+gridon'
# pio.templates

In [ ]:
index_names = ['engine', 'cycle']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names=[ "(Fan inlet temperature) (◦R)",
"(LPC outlet temperature) (◦R)",
"(HPC outlet temperature) (◦R)",
"(LPT outlet temperature) (◦R)",
"(Fan inlet Pressure) (psia)",
"(bypass-duct pressure) (psia)",
"(HPC outlet pressure) (psia)",
"(Physical fan speed) (rpm)",
"(Physical core speed) (rpm)",
"(Engine pressure ratio(P50/P2)",
"(HPC outlet Static pressure) (psia)",
"(Ratio of fuel flow to Ps30) (pps/psia)",
"(Corrected fan speed) (rpm)",
"(Corrected core speed) (rpm)",
"(Bypass Ratio)",
"(Burner fuel-air ratio)",
"(Bleed Enthalpy)",
"(Required fan speed)",
"(Required fan conversion speed)",
"(High-pressure turbines Cool air flow)",
"(Low-pressure turbines Cool air flow)" ]
col_names = index_names + setting_names + sensor_names

In [ ]:
df_train = pd.read_csv('drive/MyDrive/CMaps/train_FD002.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test = pd.read_csv('drive/MyDrive/CMaps/test_FD002.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test_RUL = pd.read_csv('drive/MyDrive/CMaps/RUL_FD002.txt',sep=r'\s+',header=None,index_col=False,names=['RUL'])

In [ ]:

# corr = df_train.corr()
# mask = np.triu(np.ones_like(corr, dtype=bool))

# f, ax = plt.subplots(figsize=(20, 20))
# cmap = sns.diverging_palette(230, 10, as_cmap=True)

# # Draw the heatmap with annotation
# sns.heatmap(
#     corr,
#     mask=mask,
#     cmap=cmap,
#     vmax=.3,
#     center=0,
#     square=True,
#     linewidths=.5,
#     cbar_kws={"shrink": .5},
#     annot=True,           # <- Add this line
#     fmt=".1f"             # <- Format the numbers to 2 decimal places
# )

# plt.show()

In [ ]:
# sens_const_values = []
# for feature in list(setting_names + sensor_names):
#     try:
#         if df_train[feature].min()==df_train[feature].max():
#             sens_const_values.append(feature)
#     except:
#         pass

# print(sens_const_values)
# df_train.drop(sens_const_values,axis=1,inplace=True)
# df_test.drop(sens_const_values,axis=1,inplace=True)

In [ ]:
# cor_matrix = df_train.corr().abs()
# upper_tri = cor_matrix.where(np.triu(np.ones(cor_matrix.shape),k=1).astype(np.bool))
# corr_features = [column for column in upper_tri.columns if any(upper_tri[column] > 0.95)]
# print(corr_features)
# df_train.drop(corr_features,axis=1,inplace=True)
# df_test.drop(corr_features,axis=1,inplace=True)

In [ ]:
features = list(df_train.columns)

In [ ]:
# # check for missing data
# for feature in features:
#     print(feature + " - " + str(len(df_train[df_train[feature].isna()])))

In [ ]:
# define the maximum life of each engine, as this could be used to obtain the RUL at each point in time of the engine's life
df_train_RUL = df_train.groupby(['engine']).agg({'cycle':'max'})
df_train_RUL.rename(columns={'cycle':'life'},inplace=True)
df_train_RUL.head()

        life
engine
1        149
2        269
3        206
4        235
5        154

In [ ]:
df_train=df_train.merge(df_train_RUL,how='left',on=['engine'])

In [ ]:
df_train['RUL']=df_train['life']-df_train['cycle']
df_train.drop(['life'],axis=1,inplace=True)

# the RUL prediction is only useful nearer to the end of the engine's life, therefore we put an upper limit on the RUL
# this is a bit sneaky, since it supposes that the test set has RULs of less than this value, the closer you are
# to the true value, the more accurate the model will be

In [ ]:
df_train['RUL'][df_train['RUL']>150]=150
df_train.head()

   engine  cycle  setting_1  setting_2  setting_3  (Fan inlet temperature) (◦R)  (LPC outlet temperature) (◦R)  (HPC outlet temperature) (◦R)  (LPT outlet temperature) (◦R)  (Fan inlet Pressure) (psia)  (bypass-duct pressure) (psia)  (HPC outlet pressure) (psia)  (Physical fan speed) (rpm)  (Physical core speed) (rpm)  (Engine pressure ratio(P50/P2)  (HPC outlet Static pressure) (psia)  (Ratio of fuel flow to Ps30) (pps/psia)  (Corrected fan speed) (rpm)  (Corrected core speed) (rpm)  (Bypass Ratio)  (Burner fuel-air ratio)  (Bleed Enthalpy)  (Required fan speed)  (Required fan conversion speed)  (High-pressure turbines Cool air flow)  (Low-pressure turbines Cool air flow)  RUL
0       1      1    34.9983     0.8400      100.0                        449.44                         555.32                        1358.61                        1137.23                         5.48                           8.00                        194.64                     2222.65                      8341.91                            1.02                                42.02                                   183.06                      2387.72                       8048.56          9.3461                     0.02               334                  2223                           100.00                                   14.73                                 8.8071  148
1       1      2    41.9982     0.8408      100.0                        445.00                         549.90                        1353.22                        1125.78                         3.91                           5.71                        138.51                     2211.57                      8303.96                            1.02                                42.20                                   130.42                      2387.66                       8072.30          9.3774                     0.02               330                  2212                           100.00                                   10.41                                 6.2665  147
2       1      3    24.9988     0.6218       60.0                        462.54                         537.31                        1256.76                        1047.45                         7.05                           9.02                        175.71                     1915.11                      8001.42                            0.94                                36.69                                   164.22                      2028.03                       7864.87         10.8941                     0.02               309                  1915                            84.93                                   14.08                                 8.6723  146
3       1      4    42.0077     0.8416      100.0                        445.00                         549.51                        1354.03                        1126.38                         3.91                           5.71                        138.46                     2211.58                      8303.96                            1.02                                41.96                                   130.72                      2387.61                       8068.66          9.3528                     0.02               329                  2212                           100.00                                   10.59                                 6.4701  145
4       1      5    25.0005     0.6203       60.0                        462.54                         537.07                        1257.71                        1047.93                         7.05                           9.03                        175.05                     1915.10                      7993.23                            0.94                                36.89                                   164.31                      2028.00                       7861.23         10.8963                     0.02               309                  1915                            84.93                                   14.13                                 8.5286  144

In [ ]:
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values
        rul_values = engine_data['RUL'].values

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)

# Scale features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
feature_cols = [col for col in df_train.columns if col not in ['engine', 'cycle', 'RUL']]
df_train[feature_cols] = scaler.fit_transform(df_train[feature_cols])
df_test[feature_cols] = scaler.transform(df_test[feature_cols])

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
# ============================================================
# ADVANCED RUL PREDICTION: Gated Ensemble BiLSTM + Attention (Optimized)
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers, callbacks, optimizers
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# MODIFIED create_sequences function to handle missing 'RUL' column for test set
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    # Check if 'RUL' column exists in the DataFrame
    has_rul = 'RUL' in df.columns

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values

        if has_rul:
            rul_values = engine_data['RUL'].values
        else:
            # If RUL column is not present (e.g., for test data), create a dummy array.
            # These 'targets' will be discarded for X_test anyway.
            rul_values = np.array([])

        # Ensure there are enough data points for the window
        if len(values) < window_size:
            continue # Skip engines that are too short for a single sequence

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            if has_rul: # Only append RUL target if RUL column exists
                targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)


CONFIG = {
    'WINDOW_SIZE': 60,
    'STRIDE': 2,
    'LSTM_UNITS': [128, 64],
    'DENSE_UNITS': 80,
    'DROPOUT_RATE': 0.3,
    'L2_REG': 0.001,
    'BATCH_SIZE': 32,
    'EPOCHS': 200,
    'LEARNING_RATE': 0.0005,
    'PATIENCE': 35,
    'N_SPLITS': 5
}

print("\nOptimized Configuration:")
for k, v in CONFIG.items():
    print(f"  {k}: {v}")


X_train, y_train, train_engine_ids = create_sequences(
    df_train, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)
X_test, _, test_engine_ids = create_sequences(
    df_test, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)

print(f"Training sequences: {X_train.shape}")
print(f"Test sequences: {X_test.shape}")


# ============================================================
# Custom Layers
# ============================================================

class GatingLayer(layers.Layer):
    def __init__(self, num_branches, **kwargs):
        super(GatingLayer, self).__init__(**kwargs)
        self.num_branches = num_branches

    def build(self, input_shape):
        self.gate_weights = self.add_weight(
            shape=(input_shape[0][-1], self.num_branches),
            initializer='glorot_uniform',
            trainable=True
        )
        self.gate_bias = self.add_weight(
            shape=(self.num_branches,),
            initializer='zeros',
            trainable=True
        )

    def call(self, inputs):
        input_stats = tf.reduce_mean(inputs[0], axis=1)
        gate_scores = tf.nn.softmax(tf.matmul(input_stats, self.gate_weights) + self.gate_bias, axis=-1)
        gate_scores = tf.expand_dims(tf.expand_dims(gate_scores, 1), -1)
        stacked = tf.stack(inputs, axis=2)
        gated = stacked * gate_scores
        fused = tf.reduce_sum(gated, axis=2)
        return fused


class AttentionLayer(layers.Layer):
    """Attention mechanism to highlight critical timesteps after fusion."""
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1]),
                                 initializer="glorot_uniform", trainable=True)
        self.b = self.add_weight(shape=(input_shape[-1],),
                                 initializer="zeros", trainable=True)
        self.u = self.add_weight(shape=(input_shape[-1],),
                                 initializer="glorot_uniform", trainable=True)

    def call(self, x):
        u_t = tf.tanh(tf.tensordot(x, self.W, axes=1) + self.b)
        attn_scores = tf.nn.softmax(tf.tensordot(u_t, self.u, axes=1), axis=1)
        attn_scores = tf.expand_dims(attn_scores, -1)
        context = tf.reduce_sum(x * attn_scores, axis=1)
        return context


# ============================================================
# Optimized Gated BiLSTM + Attention Model
# ============================================================

def build_gated_attention_bilstm(input_shape, config):
    inputs = layers.Input(shape=input_shape, name='input')

    # Parallel branches: LSTM, GRU, CNN
    branch_lstm = layers.LSTM(64, return_sequences=True,
                              kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_lstm = layers.LayerNormalization()(branch_lstm)

    branch_gru = layers.GRU(64, return_sequences=True,
                            kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_gru = layers.LayerNormalization()(branch_gru)

    branch_cnn = layers.Conv1D(64, 5, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_cnn = layers.Conv1D(64, 3, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(branch_cnn)
    branch_cnn = layers.LayerNormalization()(branch_cnn)

    fused = GatingLayer(num_branches=3)([branch_lstm, branch_gru, branch_cnn])
    fused = layers.Dropout(config['DROPOUT_RATE'])(fused)

    # BiLSTM layers for sequential modeling
    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][0],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_1'
    )(fused)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][1],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_2'
    )(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    # Attention layer
    context = AttentionLayer()(x)

    # Dense head
    x = layers.Dense(config['DENSE_UNITS'], activation='relu')(context)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    outputs = layers.Dense(1, activation='linear', name='rul_output')(x)

    model = models.Model(inputs, outputs, name='Gated_Attention_BiLSTM')

    opt = optimizers.Adam(learning_rate=config['LEARNING_RATE'])
    model.compile(
        optimizer=opt,
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=['mae', 'mse']
    )
    return model


# ============================================================
# Train with Advanced Callbacks
# ============================================================

def train_model_with_cv(X_train, y_train, engine_ids, input_shape, config, n_splits=5):
    from sklearn.model_selection import GroupKFold

    gkf = GroupKFold(n_splits=n_splits)
    results, models_list = [], []

    for fold, (tr_idx, val_idx) in enumerate(gkf.split(X_train, y_train, engine_ids), 1):
        print(f"\n{'='*25} FOLD {fold}/{n_splits} {'='*25}")
        X_tr, X_val = X_train[tr_idx], X_train[val_idx]
        y_tr, y_val = y_train[tr_idx], y_train[val_idx]

        model = build_gated_attention_bilstm(input_shape, config)

        cb = [
            callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6),
            callbacks.EarlyStopping(monitor='val_loss', patience=config['PATIENCE'],
                                    restore_best_weights=True),
            callbacks.ModelCheckpoint(f"best_fold_{fold}.h5", save_best_only=True)
        ]

        history = model.fit(
            X_tr, y_tr,
            validation_data=(X_val, y_val),
            epochs=config['EPOCHS'],
            batch_size=config['BATCH_SIZE'],
            verbose=1,
            callbacks=cb
        )

        val_loss, val_mae, val_mse = model.evaluate(X_val, y_val, verbose=0)
        val_rmse = np.sqrt(val_mse)

        y_pred = model.predict(X_val, verbose=0).flatten()
        val_r2 = r2_score(y_val, y_pred)

        results.append({'fold': fold, 'mae': val_mae, 'rmse': val_rmse, 'r2': val_r2})
        models_list.append(model)

        print(f"Fold {fold} Results -> MAE: {val_mae:.4f}, RMSE: {val_rmse:.4f}, R²: {val_r2:.4f}")

    print("\n=== Cross-Validation Summary ===")
    avg_mae = np.mean([r['mae'] for r in results])
    avg_rmse = np.mean([r['rmse'] for r in results])
    avg_r2 = np.mean([r['r2'] for r in results])
    print(f"MAE: {avg_mae:.4f}, RMSE: {avg_rmse:.4f}, R²: {avg_r2:.4f}")

    best_model_idx = np.argmax([r['r2'] for r in results])
    print(f"\nBest Fold: {best_model_idx + 1}")
    return models_list[best_model_idx], results


# ============================================================
# Execute Training
# ============================================================

input_shape = (X_train.shape[1], X_train.shape[2])
best_model, cv_results = train_model_with_cv(X_train, y_train, train_engine_ids, input_shape, CONFIG, CONFIG['N_SPLITS'])

# ============================================================
# Evaluate on Test Set
# ============================================================

y_test_pred_all = best_model.predict(X_test, verbose=0).flatten()
y_test_pred_all = np.clip(y_test_pred_all, 0, None)

# Take last window per engine
unique_engines = sorted(set(test_engine_ids))
y_true, y_pred = [], []
for eng_id in unique_engines:
    mask = test_engine_ids == eng_id
    y_pred.append(y_test_pred_all[mask][-1])
    y_true.append(df_test_RUL.iloc[int(eng_id) - 1]['RUL'])

y_true, y_pred = np.array(y_true), np.array(y_pred)
test_mae = mean_absolute_error(y_true, y_pred)
test_rmse = np.sqrt(mean_squared_error(y_true, y_pred))
test_r2 = r2_score(y_true, y_pred)

print(f"\n✅ Optimized Test Results:")
print(f"  MAE:  {test_mae:.4f}")
print(f"  RMSE: {test_rmse:.4f}")
print(f"  R²:   {test_r2:.4f}")

if test_r2 >= 0.85:
    print("\n🏆 EXCELLENT PERFORMANCE ACHIEVED!")

Optimized Configuration:
  WINDOW_SIZE: 60
  STRIDE: 2
  LSTM_UNITS: [128, 64]
  DENSE_UNITS: 80
  DROPOUT_RATE: 0.3
  L2_REG: 0.001
  BATCH_SIZE: 32
  EPOCHS: 200
  LEARNING_RATE: 0.0005
  PATIENCE: 35
  N_SPLITS: 5
Training sequences: (19277, 60, 24)
Test sequences: (9702, 60, 24)

========================= FOLD 1/5 =========================
Epoch 1/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 48.6784 - mae: 48.3419 - mse: 3684.6047

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 40s 39ms/step - loss: 48.6534 - mae: 48.3170 - mse: 3681.5278 - val_loss: 23.7993 - val_mae: 23.5740 - val_mse: 884.8427 - learning_rate: 5.0000e-04
Epoch 2/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 22.3838 - mae: 22.1646 - mse: 842.2543

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 22.3827 - mae: 22.1634 - mse: 842.1948 - val_loss: 20.3621 - val_mae: 20.1580 - val_mse: 692.0685 - learning_rate: 5.0000e-04
Epoch 3/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19.6867 - mae: 19.4848 - mse: 672.6925

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 19.6841 - mae: 19.4821 - mse: 672.5304 - val_loss: 19.1348 - val_mae: 18.9407 - val_mse: 603.0560 - learning_rate: 5.0000e-04
Epoch 4/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 17.5857 - mae: 17.3952 - mse: 551.6162

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 17.5848 - mae: 17.3942 - mse: 551.5724 - val_loss: 17.7183 - val_mae: 17.5316 - val_mse: 560.0396 - learning_rate: 5.0000e-04
Epoch 5/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 16.1349 - mae: 15.9489 - mse: 477.7837 - val_loss: 17.8554 - val_mae: 17.6747 - val_mse: 580.4044 - learning_rate: 5.0000e-04
Epoch 6/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.0801 - mae: 14.8988 - mse: 425.0412

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 15.0797 - mae: 14.8983 - mse: 425.0168 - val_loss: 16.2691 - val_mae: 16.0886 - val_mse: 498.5256 - learning_rate: 5.0000e-04
Epoch 7/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 14.0111 - mae: 13.8299 - mse: 369.0223 - val_loss: 17.8002 - val_mae: 17.6181 - val_mse: 605.3723 - learning_rate: 5.0000e-04
Epoch 8/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - loss: 13.3902 - mae: 13.2070 - mse: 339.2428 - val_loss: 17.0310 - val_mae: 16.8486 - val_mse: 563.7080 - learning_rate: 5.0000e-04
Epoch 9/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 12.3395 - mae: 12.1519 - mse: 291.2902 - val_loss: 16.9510 - val_mae: 16.7610 - val_mse: 555.8430 - learning_rate: 5.0000e-04
Epoch 10/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 11.6138 - mae: 11.4210 - mse: 261.4485 - val_loss: 18.3476 - val_mae: 18.1557 - val_mse: 638.8695 - learning_rate: 5.0000e-04
Epoch 11/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 10.8743 - mae: 10.6782 - mse: 220.3781 - val_loss: 19.1778 - val_mae: 18.9843 - val_mse: 693.4119 - learning_rate: 5.0000e-04
Epoch 12/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 10.2105 - mae: 10.0111 - mse: 191.5125 - val_loss: 19.0398 - val_mae: 18.8444 - val_mse: 677.9939 - learning_rate: 5.0000e-04
Epoch 13/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 9.7059 - mae: 9.5031 - mse: 176.2218 - val_loss: 18.9476 - val_mae: 18.7503 - val_mse: 703.7184 - learning_rate: 5.0000e-04
Epoch 14/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 9.2481 - mae: 9.0453 - mse: 158.0267 - val_loss: 19.0557 - val_mae: 18.8613 - val_mse: 723.6622 - learning_rate: 5.0000e-04
Epoch 15/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 9.2994 - mae: 9.0992 - mse: 157.2216 - val_loss: 20.1221 - val_mae: 19.9301 - val_mse: 799.1233 - learning_rate: 5.0000e-04
Epoch 16/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 8.8688 - mae: 8.6695 - mse: 146.9871 - val_loss: 18.7900 - val_mae: 18.5982 - val_mse: 680.2198 - learning_rate: 5.0000e-04
Epoch 17/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.3113 - mae: 8.1152 - mse: 126.6646 - val_loss: 19.3301 - val_mae: 19.1484 - val_mse: 707.2157 - learning_rate: 2.5000e-04
Epoch 18/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - loss: 8.1058 - mae: 7.9187 - mse: 120.6594 - val_loss: 19.6251 - val_mae: 19.4498 - val_mse: 751.5251 - learning_rate: 2.5000e-04
Epoch 19/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.9012 - mae: 7.7213 - mse: 115.5692 - val_loss: 19.8804 - val_mae: 19.7124 - val_mse: 770.9777 - learning_rate: 2.5000e-04
Epoch 20/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 7.9352 - mae: 7.7607 - mse: 118.5100 - val_loss: 18.8780 - val_mae: 18.7181 - val_mse: 694.8329 - learning_rate: 2.5000e-04
Epoch 21/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.7352 - mae: 7.5693 - mse: 112.0005 - val_loss: 19.6753 - val_mae: 19.5223 - val_mse: 744.3856 - learning_rate: 2.5000e-04
Epoch 22/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.6682 - mae: 7.5094 - mse: 111.4331 - val_loss: 19.6924 - val_mae: 19.5500 - val_mse: 731.3091 - learning_rate: 2.5000e-04
Epoch 23/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.7227 - mae: 7.5699 - mse: 113.9188 - val_loss: 18.7248 - val_mae: 18.5894 - val_mse: 657.5582 - learning_rate: 2.5000e-04
Epoch 24/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 7.6037 - mae: 7.4579 - mse: 108.5186 - val_loss: 19.3259 - val_mae: 19.1957 - val_mse: 691.2114 - learning_rate: 2.5000e-04
Epoch 25/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.5578 - mae: 7.4189 - mse: 109.5333 - val_loss: 19.2289 - val_mae: 19.1063 - val_mse: 686.3160 - learning_rate: 2.5000e-04
Epoch 26/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.4492 - mae: 7.3169 - mse: 104.9968 - val_loss: 19.4808 - val_mae: 19.3633 - val_mse: 732.9619 - learning_rate: 2.5000e-04
Epoch 27/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.2758 - mae: 7.1467 - mse: 101.2778 - val_loss: 19.0920 - val_mae: 18.9786 - val_mse: 697.7477 - learning_rate: 1.2500e-04
Epoch 28/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 7.0936 - mae: 6.9707 - mse: 96.9840 - val_loss: 19.3793 - val_mae: 19.2712 - val_mse: 720.5242 - learning_rate: 1.2500e-04
Epoch 29/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.0243 - mae: 6.9062 - mse: 96.1655 - val_loss: 19.0912 - val_mae: 18.9897 - val_mse: 679.0646 - learning_rate: 1.2500e-04
Epoch 30/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 7.1513 - mae: 7.0389 - mse: 98.2253 - val_loss: 19.6455 - val_mae: 19.5493 - val_mse: 752.3649 - learning_rate: 1.2500e-04
Epoch 31/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.0642 - mae: 6.9559 - mse: 96.7730 - val_loss: 19.4360 - val_mae: 19.3445 - val_mse: 726.1576 - learning_rate: 1.2500e-04
Epoch 32/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.0178 - mae: 6.9132 - mse: 95.3979 - val_loss: 19.3369 - val_mae: 19.2506 - val_mse: 691.0786 - learning_rate: 1.2500e-04
Epoch 33/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.0529 - mae: 6.9544 - mse: 96.5548 - val_loss: 19.3813 - val_mae: 19.2977 - val_mse: 722.0957 - learning_rate: 1.2500e-04
Epoch 34/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 7.0219 - mae: 6.9280 - mse: 96.2674 - val_loss: 19.3802 - val_mae: 19.3017 - val_mse: 711.8508 - learning_rate: 1.2500e-04
Epoch 35/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.0670 - mae: 6.9766 - mse: 96.5823 - val_loss: 19.6310 - val_mae: 19.5567 - val_mse: 734.1989 - learning_rate: 1.2500e-04
Epoch 36/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 6.9979 - mae: 6.9118 - mse: 97.2706 - val_loss: 19.2295 - val_mae: 19.1591 - val_mse: 730.2935 - learning_rate: 1.2500e-04
Epoch 37/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 6.9165 - mae: 6.8329 - mse: 94.2946 - val_loss: 19.5983 - val_mae: 19.5301 - val_mse: 748.1972 - learning_rate: 6.2500e-05
Epoch 38/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 6.9711 - mae: 6.8899 - mse: 96.7863 - val_loss: 19.4810 - val_mae: 19.4156 - val_mse: 725.3875 - learning_rate: 6.2500e-05
Epoch 39/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.8982 - mae: 6.8205 - mse: 94.8582 - val_loss: 19.3850 - val_mae: 19.3230 - val_mse: 726.9695 - learning_rate: 6.2500e-05
Epoch 40/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.9114 - mae: 6.8348 - mse: 95.5482 - val_loss: 19.2359 - val_mae: 19.1747 - val_mse: 717.7111 - learning_rate: 6.2500e-05
Epoch 41/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.6880 - mae: 6.6138 - mse: 88.5621 - val_loss: 19.3078 - val_mae: 19.2501 - val_mse: 716.8336 - learning_rate: 6.2500e-05
Fold 1 Results -> MAE: 16.0886, RMSE: 22.3277, R²: 0.7699

========================= FOLD 2/5 =========================
Epoch 1/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 46.6990 - mae: 46.3401 - mse: 3461.7505

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 26s 37ms/step - loss: 46.6747 - mae: 46.3159 - mse: 3458.7974 - val_loss: 22.7498 - val_mae: 22.4789 - val_mse: 805.4701 - learning_rate: 5.0000e-04
Epoch 2/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 22.6528 - mae: 22.3892 - mse: 854.4968

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - loss: 22.6496 - mae: 22.3860 - mse: 854.2982 - val_loss: 19.9676 - val_mae: 19.7224 - val_mse: 613.8333 - learning_rate: 5.0000e-04
Epoch 3/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19.9552 - mae: 19.7176 - mse: 679.8754

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 34ms/step - loss: 19.9533 - mae: 19.7157 - mse: 679.7719 - val_loss: 17.4396 - val_mae: 17.2181 - val_mse: 483.3779 - learning_rate: 5.0000e-04
Epoch 4/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 17.3214 - mae: 17.1049 - mse: 531.2762

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 17.3204 - mae: 17.1039 - mse: 531.2402 - val_loss: 15.9845 - val_mae: 15.7820 - val_mse: 417.8159 - learning_rate: 5.0000e-04
Epoch 5/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 16.4132 - mae: 16.2144 - mse: 484.8279 - val_loss: 16.9742 - val_mae: 16.7892 - val_mse: 506.7035 - learning_rate: 5.0000e-04
Epoch 6/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 15.2916 - mae: 15.1074 - mse: 427.1396 - val_loss: 17.2925 - val_mae: 17.1172 - val_mse: 539.5114 - learning_rate: 5.0000e-04
Epoch 7/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 14.4489 - mae: 14.2733 - mse: 388.8070 - val_loss: 16.7628 - val_mae: 16.5949 - val_mse: 486.8000 - learning_rate: 5.0000e-04
Epoch 8/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 13.7648 - mae: 13.5913 - mse: 360.9968 - val_loss: 16.5288 - val_mae: 16.3606 - val_mse: 499.3541 - learning_rate: 5.0000e-04
Epoch 9/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 12.7997 - mae: 12.6276 - mse: 310.8811 - val_loss: 17.3056 - val_mae: 17.1327 - val_mse: 548.5977 - learning_rate: 5.0000e-04
Epoch 10/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 12.1200 - mae: 11.9430 - mse: 278.0082 - val_loss: 18.8534 - val_mae: 18.6766 - val_mse: 619.0938 - learning_rate: 5.0000e-04
Epoch 11/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 11.5887 - mae: 11.4047 - mse: 248.6063 - val_loss: 17.6831 - val_mae: 17.4991 - val_mse: 571.3032 - learning_rate: 5.0000e-04
Epoch 12/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 10.9839 - mae: 10.7940 - mse: 225.4632 - val_loss: 18.2094 - val_mae: 18.0227 - val_mse: 610.4708 - learning_rate: 5.0000e-04
Epoch 13/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 10.4367 - mae: 10.2438 - mse: 203.9160 - val_loss: 16.9061 - val_mae: 16.7174 - val_mse: 532.3927 - learning_rate: 5.0000e-04
Epoch 14/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - loss: 10.0136 - mae: 9.8186 - mse: 185.2649 - val_loss: 17.7817 - val_mae: 17.5881 - val_mse: 571.5440 - learning_rate: 5.0000e-04
Epoch 15/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 9.0835 - mae: 8.8838 - mse: 153.5546 - val_loss: 16.9551 - val_mae: 16.7679 - val_mse: 554.4980 - learning_rate: 2.5000e-04
Epoch 16/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 8.5501 - mae: 8.3564 - mse: 135.9238 - val_loss: 16.6621 - val_mae: 16.4795 - val_mse: 540.7120 - learning_rate: 2.5000e-04
Epoch 17/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 8.4415 - mae: 8.2542 - mse: 130.8325 - val_loss: 17.4922 - val_mae: 17.3178 - val_mse: 561.8386 - learning_rate: 2.5000e-04
Epoch 18/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.4096 - mae: 8.2285 - mse: 130.0280 - val_loss: 16.9897 - val_mae: 16.8221 - val_mse: 536.3509 - learning_rate: 2.5000e-04
Epoch 19/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.2864 - mae: 8.1099 - mse: 127.8423 - val_loss: 16.9667 - val_mae: 16.8047 - val_mse: 544.0189 - learning_rate: 2.5000e-04
Epoch 20/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 8.3654 - mae: 8.1959 - mse: 132.3616 - val_loss: 17.4758 - val_mae: 17.3179 - val_mse: 579.8334 - learning_rate: 2.5000e-04
Epoch 21/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.1363 - mae: 7.9725 - mse: 123.8227 - val_loss: 17.7506 - val_mae: 17.5988 - val_mse: 601.9708 - learning_rate: 2.5000e-04
Epoch 22/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 7.9753 - mae: 7.8163 - mse: 118.3186 - val_loss: 16.9574 - val_mae: 16.8109 - val_mse: 533.1008 - learning_rate: 2.5000e-04
Epoch 23/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 7.9452 - mae: 7.7905 - mse: 117.7883 - val_loss: 17.1085 - val_mae: 16.9686 - val_mse: 547.6241 - learning_rate: 2.5000e-04
Epoch 24/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.8574 - mae: 7.7086 - mse: 115.0407 - val_loss: 17.1459 - val_mae: 17.0087 - val_mse: 570.2004 - learning_rate: 2.5000e-04
Epoch 25/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.5537 - mae: 7.4091 - mse: 106.8123 - val_loss: 16.8487 - val_mae: 16.7178 - val_mse: 530.4479 - learning_rate: 1.2500e-04
Epoch 26/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 7.4002 - mae: 7.2583 - mse: 104.5452 - val_loss: 16.8255 - val_mae: 16.7002 - val_mse: 536.0269 - learning_rate: 1.2500e-04
Epoch 27/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - loss: 7.3595 - mae: 7.2227 - mse: 104.2415 - val_loss: 17.0836 - val_mae: 16.9623 - val_mse: 555.9498 - learning_rate: 1.2500e-04
Epoch 28/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.2786 - mae: 7.1471 - mse: 99.6462 - val_loss: 17.5112 - val_mae: 17.3942 - val_mse: 572.2700 - learning_rate: 1.2500e-04
Epoch 29/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.4438 - mae: 7.3159 - mse: 105.7229 - val_loss: 16.8921 - val_mae: 16.7783 - val_mse: 545.2017 - learning_rate: 1.2500e-04
Epoch 30/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - loss: 7.3239 - mae: 7.1980 - mse: 102.2055 - val_loss: 17.0531 - val_mae: 16.9456 - val_mse: 543.4107 - learning_rate: 1.2500e-04
Epoch 31/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.2651 - mae: 7.1462 - mse: 100.1338 - val_loss: 17.4200 - val_mae: 17.3168 - val_mse: 575.2340 - learning_rate: 1.2500e-04
Epoch 32/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.2940 - mae: 7.1778 - mse: 102.9682 - val_loss: 17.5925 - val_mae: 17.4929 - val_mse: 576.1404 - learning_rate: 1.2500e-04
Epoch 33/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.1023 - mae: 6.9900 - mse: 96.9598 - val_loss: 17.6709 - val_mae: 17.5752 - val_mse: 592.3326 - learning_rate: 1.2500e-04
Epoch 34/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 7.1869 - mae: 7.0800 - mse: 99.2085 - val_loss: 17.9860 - val_mae: 17.8951 - val_mse: 592.3798 - learning_rate: 1.2500e-04
Epoch 35/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.1207 - mae: 7.0167 - mse: 98.9740 - val_loss: 17.7791 - val_mae: 17.6900 - val_mse: 584.9867 - learning_rate: 6.2500e-05
Epoch 36/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 7.0375 - mae: 6.9346 - mse: 97.0923 - val_loss: 17.0913 - val_mae: 17.0055 - val_mse: 549.0615 - learning_rate: 6.2500e-05
Epoch 37/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 35ms/step - loss: 7.0548 - mae: 6.9537 - mse: 96.2576 - val_loss: 17.2262 - val_mae: 17.1424 - val_mse: 561.3964 - learning_rate: 6.2500e-05
Epoch 38/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 6.9636 - mae: 6.8671 - mse: 94.9896 - val_loss: 17.3617 - val_mae: 17.2810 - val_mse: 571.4240 - learning_rate: 6.2500e-05
Epoch 39/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.9654 - mae: 6.8695 - mse: 95.2081 - val_loss: 17.3232 - val_mae: 17.2427 - val_mse: 578.8422 - learning_rate: 6.2500e-05
Fold 2 Results -> MAE: 15.7820, RMSE: 20.4405, R²: 0.8071

========================= FOLD 3/5 =========================
Epoch 1/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 47.5301 - mae: 47.1941 - mse: 3509.0818

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 27s 37ms/step - loss: 47.5073 - mae: 47.1714 - mse: 3506.2688 - val_loss: 23.8253 - val_mae: 23.6174 - val_mse: 903.6349 - learning_rate: 5.0000e-04
Epoch 2/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 22.8696 - mae: 22.6714 - mse: 866.2888

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 22.8679 - mae: 22.6697 - mse: 866.1793 - val_loss: 19.9068 - val_mae: 19.7340 - val_mse: 647.4552 - learning_rate: 5.0000e-04
Epoch 3/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 19.3467 - mae: 19.1806 - mse: 657.5812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 19.3457 - mae: 19.1797 - mse: 657.5231 - val_loss: 18.5254 - val_mae: 18.3824 - val_mse: 607.6445 - learning_rate: 5.0000e-04
Epoch 4/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 17.5205 - mae: 17.3834 - mse: 555.0691

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 17.5195 - mae: 17.3824 - mse: 555.0114 - val_loss: 16.9219 - val_mae: 16.8051 - val_mse: 528.0717 - learning_rate: 5.0000e-04
Epoch 5/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 16.6720 - mae: 16.5604 - mse: 508.7940

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 16.6713 - mae: 16.5598 - mse: 508.7572 - val_loss: 15.2559 - val_mae: 15.1572 - val_mse: 419.2191 - learning_rate: 5.0000e-04
Epoch 6/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 15.7014 - mae: 15.6061 - mse: 460.3631 - val_loss: 15.3633 - val_mae: 15.2817 - val_mse: 425.6805 - learning_rate: 5.0000e-04
Epoch 7/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 15.1854 - mae: 15.1026 - mse: 427.1557

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 15.1844 - mae: 15.1016 - mse: 427.1151 - val_loss: 14.5900 - val_mae: 14.5117 - val_mse: 407.5060 - learning_rate: 5.0000e-04
Epoch 8/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 14.2694 - mae: 14.1936 - mse: 386.3763 - val_loss: 14.5948 - val_mae: 14.5224 - val_mse: 394.6833 - learning_rate: 5.0000e-04
Epoch 9/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 13.5013 - mae: 13.4290 - mse: 352.9875 - val_loss: 15.1842 - val_mae: 15.1147 - val_mse: 446.6132 - learning_rate: 5.0000e-04
Epoch 10/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 13.0568 - mae: 12.9856 - mse: 327.3568 - val_loss: 16.4947 - val_mae: 16.4248 - val_mse: 505.2427 - learning_rate: 5.0000e-04
Epoch 11/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 12.5010 - mae: 12.4283 - mse: 304.1879 - val_loss: 14.8048 - val_mae: 14.7299 - val_mse: 422.3483 - learning_rate: 5.0000e-04
Epoch 12/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 11.8128 - mae: 11.7350 - mse: 273.0145 - val_loss: 15.8794 - val_mae: 15.7981 - val_mse: 497.5976 - learning_rate: 5.0000e-04
Epoch 13/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 11.5550 - mae: 11.4689 - mse: 255.1447 - val_loss: 15.9441 - val_mae: 15.8569 - val_mse: 481.5165 - learning_rate: 5.0000e-04
Epoch 14/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 10.8435 - mae: 10.7493 - mse: 225.4889 - val_loss: 14.9850 - val_mae: 14.8869 - val_mse: 432.1827 - learning_rate: 5.0000e-04
Epoch 15/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 10.1104 - mae: 10.0062 - mse: 194.8094 - val_loss: 15.0324 - val_mae: 14.9251 - val_mse: 450.2911 - learning_rate: 5.0000e-04
Epoch 16/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 9.6274 - mae: 9.5139 - mse: 177.7946 - val_loss: 15.8954 - val_mae: 15.7840 - val_mse: 470.2662 - learning_rate: 5.0000e-04
Epoch 17/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 9.5450 - mae: 9.4272 - mse: 168.5894 - val_loss: 15.2875 - val_mae: 15.1683 - val_mse: 443.5996 - learning_rate: 5.0000e-04
Epoch 18/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 8.3597 - mae: 8.2350 - mse: 131.1178 - val_loss: 15.2507 - val_mae: 15.1373 - val_mse: 450.7603 - learning_rate: 2.5000e-04
Epoch 19/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 8.0861 - mae: 7.9674 - mse: 121.9474 - val_loss: 15.6574 - val_mae: 15.5487 - val_mse: 485.9254 - learning_rate: 2.5000e-04
Epoch 20/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 7.8182 - mae: 7.7023 - mse: 115.3045 - val_loss: 15.9224 - val_mae: 15.8188 - val_mse: 489.9638 - learning_rate: 2.5000e-04
Epoch 21/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 7.8178 - mae: 7.7058 - mse: 114.9641 - val_loss: 15.3364 - val_mae: 15.2341 - val_mse: 456.6434 - learning_rate: 2.5000e-04
Epoch 22/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 7.7100 - mae: 7.6033 - mse: 110.5877 - val_loss: 16.4815 - val_mae: 16.3844 - val_mse: 544.1492 - learning_rate: 2.5000e-04
Epoch 23/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.5295 - mae: 7.4250 - mse: 106.3896 - val_loss: 15.9080 - val_mae: 15.8144 - val_mse: 488.3750 - learning_rate: 2.5000e-04
Epoch 24/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.5811 - mae: 7.4805 - mse: 108.1617 - val_loss: 15.9652 - val_mae: 15.8750 - val_mse: 506.6074 - learning_rate: 2.5000e-04
Epoch 25/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.3185 - mae: 7.2208 - mse: 99.3687 - val_loss: 16.2962 - val_mae: 16.2115 - val_mse: 503.1062 - learning_rate: 2.5000e-04
Epoch 26/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 7.3304 - mae: 7.2378 - mse: 101.0783 - val_loss: 16.0786 - val_mae: 15.9948 - val_mse: 509.2173 - learning_rate: 2.5000e-04
Epoch 27/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.3173 - mae: 7.2265 - mse: 101.5306 - val_loss: 16.4146 - val_mae: 16.3364 - val_mse: 520.6317 - learning_rate: 2.5000e-04
Epoch 28/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.9899 - mae: 6.9013 - mse: 92.3593 - val_loss: 15.9929 - val_mae: 15.9165 - val_mse: 501.7739 - learning_rate: 1.2500e-04
Epoch 29/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.8234 - mae: 6.7380 - mse: 88.9087 - val_loss: 15.7127 - val_mae: 15.6393 - val_mse: 485.8344 - learning_rate: 1.2500e-04
Epoch 30/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.8590 - mae: 6.7778 - mse: 90.8727 - val_loss: 16.0576 - val_mae: 15.9903 - val_mse: 516.2563 - learning_rate: 1.2500e-04
Epoch 31/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 6.8529 - mae: 6.7759 - mse: 89.2938 - val_loss: 16.3269 - val_mae: 16.2646 - val_mse: 512.8760 - learning_rate: 1.2500e-04
Epoch 32/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 6.8598 - mae: 6.7845 - mse: 92.2907 - val_loss: 16.5446 - val_mae: 16.4833 - val_mse: 531.3632 - learning_rate: 1.2500e-04
Epoch 33/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.7709 - mae: 6.6986 - mse: 90.0523 - val_loss: 16.0978 - val_mae: 16.0404 - val_mse: 505.3447 - learning_rate: 1.2500e-04
Epoch 34/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 6.7738 - mae: 6.7064 - mse: 87.8993 - val_loss: 15.8166 - val_mae: 15.7622 - val_mse: 483.7373 - learning_rate: 1.2500e-04
Epoch 35/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 6.6937 - mae: 6.6280 - mse: 86.4979 - val_loss: 15.8679 - val_mae: 15.8146 - val_mse: 508.0450 - learning_rate: 1.2500e-04
Epoch 36/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.7555 - mae: 6.6928 - mse: 89.5494 - val_loss: 15.9157 - val_mae: 15.8672 - val_mse: 494.5319 - learning_rate: 1.2500e-04
Epoch 37/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 6.7616 - mae: 6.7024 - mse: 90.1139 - val_loss: 16.6036 - val_mae: 16.5582 - val_mse: 542.6982 - learning_rate: 1.2500e-04
Epoch 38/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.5590 - mae: 6.5015 - mse: 84.0557 - val_loss: 15.8799 - val_mae: 15.8356 - val_mse: 506.9373 - learning_rate: 6.2500e-05
Epoch 39/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.4930 - mae: 6.4387 - mse: 82.2262 - val_loss: 15.9156 - val_mae: 15.8751 - val_mse: 506.3021 - learning_rate: 6.2500e-05
Epoch 40/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 35ms/step - loss: 6.3661 - mae: 6.3105 - mse: 80.4348 - val_loss: 15.9255 - val_mae: 15.8866 - val_mse: 507.4486 - learning_rate: 6.2500e-05
Epoch 41/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.4219 - mae: 6.3706 - mse: 83.2200 - val_loss: 15.9132 - val_mae: 15.8754 - val_mse: 508.9361 - learning_rate: 6.2500e-05
Epoch 42/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.3910 - mae: 6.3407 - mse: 80.6444 - val_loss: 15.8564 - val_mae: 15.8216 - val_mse: 505.0719 - learning_rate: 6.2500e-05
Fold 3 Results -> MAE: 14.5117, RMSE: 20.1868, R²: 0.8121

========================= FOLD 4/5 =========================
Epoch 1/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 46.8801 - mae: 46.5338 - mse: 3542.3931

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 26s 38ms/step - loss: 46.8546 - mae: 46.5084 - mse: 3539.2461 - val_loss: 20.9073 - val_mae: 20.6547 - val_mse: 680.1080 - learning_rate: 5.0000e-04
Epoch 2/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 22.1342 - mae: 21.8911 - mse: 820.5635

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 22.1303 - mae: 21.8872 - mse: 820.3246 - val_loss: 17.7260 - val_mae: 17.5029 - val_mse: 553.9187 - learning_rate: 5.0000e-04
Epoch 3/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 18.6525 - mae: 18.4356 - mse: 608.3536

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 18.6512 - mae: 18.4343 - mse: 608.2856 - val_loss: 17.0044 - val_mae: 16.8036 - val_mse: 546.0668 - learning_rate: 5.0000e-04
Epoch 4/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 16.7828 - mae: 16.5903 - mse: 507.7074

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 16.7810 - mae: 16.5886 - mse: 507.6105 - val_loss: 16.9814 - val_mae: 16.8049 - val_mse: 503.3912 - learning_rate: 5.0000e-04
Epoch 5/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.9724 - mae: 15.7983 - mse: 462.0523

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 15.9721 - mae: 15.7980 - mse: 462.0393 - val_loss: 14.6706 - val_mae: 14.5015 - val_mse: 394.9955 - learning_rate: 5.0000e-04
Epoch 6/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - loss: 15.2228 - mae: 15.0614 - mse: 427.3749 - val_loss: 15.9291 - val_mae: 15.7750 - val_mse: 460.5233 - learning_rate: 5.0000e-04
Epoch 7/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 14.5192 - mae: 14.3654 - mse: 395.9126 - val_loss: 16.3142 - val_mae: 16.1644 - val_mse: 503.3315 - learning_rate: 5.0000e-04
Epoch 8/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 13.5561 - mae: 13.4063 - mse: 349.4161 - val_loss: 16.1298 - val_mae: 15.9847 - val_mse: 464.0894 - learning_rate: 5.0000e-04
Epoch 9/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 39ms/step - loss: 12.9399 - mae: 12.7932 - mse: 319.8277 - val_loss: 15.5492 - val_mae: 15.4005 - val_mse: 479.4955 - learning_rate: 5.0000e-04
Epoch 10/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 12.0129 - mae: 11.8650 - mse: 272.1260 - val_loss: 15.3625 - val_mae: 15.2120 - val_mse: 460.2050 - learning_rate: 5.0000e-04
Epoch 11/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 11.3243 - mae: 11.1713 - mse: 244.2075

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 11.3243 - mae: 11.1714 - mse: 244.2027 - val_loss: 14.3219 - val_mae: 14.1655 - val_mse: 401.7762 - learning_rate: 5.0000e-04
Epoch 12/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 10.8743 - mae: 10.7157 - mse: 224.8935 - val_loss: 16.5368 - val_mae: 16.3757 - val_mse: 511.4286 - learning_rate: 5.0000e-04
Epoch 13/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 10.3783 - mae: 10.2119 - mse: 202.9526 - val_loss: 15.5421 - val_mae: 15.3735 - val_mse: 483.4883 - learning_rate: 5.0000e-04
Epoch 14/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 9.9292 - mae: 9.7565 - mse: 191.2356 - val_loss: 16.6823 - val_mae: 16.5130 - val_mse: 551.2430 - learning_rate: 5.0000e-04
Epoch 15/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 9.5061 - mae: 9.3292 - mse: 166.8846 - val_loss: 15.1765 - val_mae: 14.9991 - val_mse: 439.7690 - learning_rate: 5.0000e-04
Epoch 16/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 9.3489 - mae: 9.1654 - mse: 161.1517 - val_loss: 16.1566 - val_mae: 15.9752 - val_mse: 517.0211 - learning_rate: 5.0000e-04
Epoch 17/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - loss: 8.8941 - mae: 8.7089 - mse: 146.0409 - val_loss: 16.5520 - val_mae: 16.3726 - val_mse: 526.6453 - learning_rate: 5.0000e-04
Epoch 18/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 8.7680 - mae: 8.5794 - mse: 141.6228 - val_loss: 16.1455 - val_mae: 15.9617 - val_mse: 506.6562 - learning_rate: 5.0000e-04
Epoch 19/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 8.5336 - mae: 8.3444 - mse: 135.0278 - val_loss: 17.0196 - val_mae: 16.8373 - val_mse: 536.4698 - learning_rate: 5.0000e-04
Epoch 20/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 8.3015 - mae: 8.1107 - mse: 125.1707 - val_loss: 16.9493 - val_mae: 16.7680 - val_mse: 544.2811 - learning_rate: 5.0000e-04
Epoch 21/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.0344 - mae: 7.8445 - mse: 118.0403 - val_loss: 16.8969 - val_mae: 16.7142 - val_mse: 558.8138 - learning_rate: 5.0000e-04
Epoch 22/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 7.2424 - mae: 7.0523 - mse: 97.3087 - val_loss: 16.6813 - val_mae: 16.5071 - val_mse: 542.8729 - learning_rate: 2.5000e-04
Epoch 23/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.2134 - mae: 7.0335 - mse: 95.1686 - val_loss: 17.3316 - val_mae: 17.1674 - val_mse: 555.3104 - learning_rate: 2.5000e-04
Epoch 24/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 7.0864 - mae: 6.9111 - mse: 92.7330 - val_loss: 16.7046 - val_mae: 16.5452 - val_mse: 560.3061 - learning_rate: 2.5000e-04
Epoch 25/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 34ms/step - loss: 7.0796 - mae: 6.9146 - mse: 91.8959 - val_loss: 16.3332 - val_mae: 16.1811 - val_mse: 537.0287 - learning_rate: 2.5000e-04
Epoch 26/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.9516 - mae: 6.7925 - mse: 90.6988 - val_loss: 16.7049 - val_mae: 16.5604 - val_mse: 547.7015 - learning_rate: 2.5000e-04
Epoch 27/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.9007 - mae: 6.7481 - mse: 88.5914 - val_loss: 16.9538 - val_mae: 16.8169 - val_mse: 566.7793 - learning_rate: 2.5000e-04
Epoch 28/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.9871 - mae: 6.8407 - mse: 91.4520 - val_loss: 16.9301 - val_mae: 16.7988 - val_mse: 563.7445 - learning_rate: 2.5000e-04
Epoch 29/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.8138 - mae: 6.6749 - mse: 87.3688 - val_loss: 17.4064 - val_mae: 17.2809 - val_mse: 585.4284 - learning_rate: 2.5000e-04
Epoch 30/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 36ms/step - loss: 6.9018 - mae: 6.7694 - mse: 89.0889 - val_loss: 17.0499 - val_mae: 16.9343 - val_mse: 567.2740 - learning_rate: 2.5000e-04
Epoch 31/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.9778 - mae: 6.8507 - mse: 90.3382 - val_loss: 16.9404 - val_mae: 16.8284 - val_mse: 561.4012 - learning_rate: 2.5000e-04
Epoch 32/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.5820 - mae: 6.4589 - mse: 82.9629 - val_loss: 16.9334 - val_mae: 16.8278 - val_mse: 569.2379 - learning_rate: 1.2500e-04
Epoch 33/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.5066 - mae: 6.3877 - mse: 81.6623 - val_loss: 17.0241 - val_mae: 16.9204 - val_mse: 562.2902 - learning_rate: 1.2500e-04
Epoch 34/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 6.4590 - mae: 6.3437 - mse: 80.5258 - val_loss: 17.1107 - val_mae: 17.0128 - val_mse: 558.8867 - learning_rate: 1.2500e-04
Epoch 35/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.5165 - mae: 6.4068 - mse: 80.9650 - val_loss: 17.3017 - val_mae: 17.2052 - val_mse: 577.0445 - learning_rate: 1.2500e-04
Epoch 36/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 6.5730 - mae: 6.4695 - mse: 81.9155 - val_loss: 16.7773 - val_mae: 16.6892 - val_mse: 549.9338 - learning_rate: 1.2500e-04
Epoch 37/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.3767 - mae: 6.2762 - mse: 78.0803 - val_loss: 16.9972 - val_mae: 16.9130 - val_mse: 558.6492 - learning_rate: 1.2500e-04
Epoch 38/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 6.3840 - mae: 6.2875 - mse: 78.8360 - val_loss: 16.8612 - val_mae: 16.7821 - val_mse: 547.3652 - learning_rate: 1.2500e-04
Epoch 39/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.4244 - mae: 6.3336 - mse: 81.4860 - val_loss: 16.7315 - val_mae: 16.6567 - val_mse: 556.3561 - learning_rate: 1.2500e-04
Epoch 40/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.4135 - mae: 6.3268 - mse: 80.4354 - val_loss: 17.2929 - val_mae: 17.2224 - val_mse: 574.3104 - learning_rate: 1.2500e-04
Epoch 41/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.2375 - mae: 6.1544 - mse: 75.7038 - val_loss: 17.3131 - val_mae: 17.2461 - val_mse: 580.1507 - learning_rate: 1.2500e-04
Epoch 42/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 6.3711 - mae: 6.2922 - mse: 80.2281 - val_loss: 17.0143 - val_mae: 16.9498 - val_mse: 567.0817 - learning_rate: 6.2500e-05
Epoch 43/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 6.2915 - mae: 6.2143 - mse: 77.2898 - val_loss: 17.0255 - val_mae: 16.9659 - val_mse: 571.9601 - learning_rate: 6.2500e-05
Epoch 44/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 6.2851 - mae: 6.2104 - mse: 76.5739 - val_loss: 17.0563 - val_mae: 16.9983 - val_mse: 572.0732 - learning_rate: 6.2500e-05
Epoch 45/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - loss: 6.0648 - mae: 5.9921 - mse: 73.3107 - val_loss: 17.0828 - val_mae: 17.0273 - val_mse: 569.7500 - learning_rate: 6.2500e-05
Epoch 46/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 6.2143 - mae: 6.1454 - mse: 75.4730 - val_loss: 16.9310 - val_mae: 16.8780 - val_mse: 557.2883 - learning_rate: 6.2500e-05
Fold 4 Results -> MAE: 14.1655, RMSE: 20.0444, R²: 0.8144

========================= FOLD 5/5 =========================
Epoch 1/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 49.4186 - mae: 49.0850 - mse: 3822.8408

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 27s 40ms/step - loss: 49.3942 - mae: 49.0607 - mse: 3819.7095 - val_loss: 22.7859 - val_mae: 22.5593 - val_mse: 887.6240 - learning_rate: 5.0000e-04
Epoch 2/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 24.4062 - mae: 24.1867 - mse: 974.9919

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 24.4027 - mae: 24.1832 - mse: 974.7610 - val_loss: 21.1393 - val_mae: 20.9421 - val_mse: 757.8615 - learning_rate: 5.0000e-04
Epoch 3/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 21.7276 - mae: 21.5407 - mse: 788.8549

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 21.7256 - mae: 21.5387 - mse: 788.7711 - val_loss: 20.4650 - val_mae: 20.2985 - val_mse: 693.6677 - learning_rate: 5.0000e-04
Epoch 4/200
481/482 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 19.6820 - mae: 19.5245 - mse: 670.1995

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 19.6795 - mae: 19.5220 - mse: 670.0827 - val_loss: 16.2449 - val_mae: 16.1011 - val_mse: 459.2202 - learning_rate: 5.0000e-04
Epoch 5/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 17.7635 - mae: 17.6262 - mse: 569.6126 - val_loss: 17.0902 - val_mae: 16.9663 - val_mse: 485.5486 - learning_rate: 5.0000e-04
Epoch 6/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 16.7342 - mae: 16.6148 - mse: 507.6334 - val_loss: 17.7493 - val_mae: 17.6475 - val_mse: 556.1771 - learning_rate: 5.0000e-04
Epoch 7/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.8705 - mae: 15.7720 - mse: 462.3988

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 15.8697 - mae: 15.7713 - mse: 462.3650 - val_loss: 15.8708 - val_mae: 15.7835 - val_mse: 454.6179 - learning_rate: 5.0000e-04
Epoch 8/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.3336 - mae: 15.2494 - mse: 434.0508

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 15.3333 - mae: 15.2491 - mse: 434.0446 - val_loss: 15.3490 - val_mae: 15.2748 - val_mse: 433.6159 - learning_rate: 5.0000e-04
Epoch 9/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 14.3128 - mae: 14.2379 - mse: 386.7562 - val_loss: 16.0952 - val_mae: 16.0267 - val_mse: 484.8582 - learning_rate: 5.0000e-04
Epoch 10/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 13.5315 - mae: 13.4635 - mse: 348.6704 - val_loss: 16.7149 - val_mae: 16.6512 - val_mse: 536.1448 - learning_rate: 5.0000e-04
Epoch 11/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 13.1350 - mae: 13.0708 - mse: 328.0462 - val_loss: 17.0268 - val_mae: 16.9659 - val_mse: 563.4403 - learning_rate: 5.0000e-04
Epoch 12/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 12.6972 - mae: 12.6349 - mse: 306.3386 - val_loss: 18.0691 - val_mae: 18.0099 - val_mse: 661.0949 - learning_rate: 5.0000e-04
Epoch 13/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 12.2805 - mae: 12.2191 - mse: 284.2584 - val_loss: 17.4083 - val_mae: 17.3503 - val_mse: 614.3953 - learning_rate: 5.0000e-04
Epoch 14/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 11.5346 - mae: 11.4725 - mse: 255.2419 - val_loss: 17.3430 - val_mae: 17.2853 - val_mse: 584.0129 - learning_rate: 5.0000e-04
Epoch 15/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 10.9464 - mae: 10.8848 - mse: 228.2863 - val_loss: 17.8205 - val_mae: 17.7606 - val_mse: 628.5136 - learning_rate: 5.0000e-04
Epoch 16/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 10.6191 - mae: 10.5544 - mse: 213.4543 - val_loss: 17.1502 - val_mae: 17.0878 - val_mse: 571.3953 - learning_rate: 5.0000e-04
Epoch 17/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 10.1212 - mae: 10.0555 - mse: 193.0117 - val_loss: 18.2503 - val_mae: 18.1866 - val_mse: 647.1108 - learning_rate: 5.0000e-04
Epoch 18/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 10.1494 - mae: 10.0813 - mse: 198.2989 - val_loss: 17.7601 - val_mae: 17.6982 - val_mse: 626.6667 - learning_rate: 5.0000e-04
Epoch 19/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 9.1057 - mae: 9.0371 - mse: 157.9343 - val_loss: 17.2868 - val_mae: 17.2305 - val_mse: 582.4430 - learning_rate: 2.5000e-04
Epoch 20/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.5567 - mae: 8.4919 - mse: 142.3052 - val_loss: 18.6800 - val_mae: 18.6272 - val_mse: 673.3429 - learning_rate: 2.5000e-04
Epoch 21/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 8.6807 - mae: 8.6217 - mse: 145.5572 - val_loss: 17.4664 - val_mae: 17.4197 - val_mse: 587.3212 - learning_rate: 2.5000e-04
Epoch 22/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.5078 - mae: 8.4548 - mse: 139.2086 - val_loss: 18.2230 - val_mae: 18.1816 - val_mse: 639.3018 - learning_rate: 2.5000e-04
Epoch 23/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 8.3986 - mae: 8.3495 - mse: 137.0950 - val_loss: 17.9314 - val_mae: 17.8946 - val_mse: 607.0876 - learning_rate: 2.5000e-04
Epoch 24/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 8.3644 - mae: 8.3208 - mse: 133.3643 - val_loss: 17.7436 - val_mae: 17.7104 - val_mse: 636.1024 - learning_rate: 2.5000e-04
Epoch 25/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 8.2798 - mae: 8.2418 - mse: 132.0949 - val_loss: 17.9891 - val_mae: 17.9594 - val_mse: 626.4304 - learning_rate: 2.5000e-04
Epoch 26/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 35ms/step - loss: 8.1315 - mae: 8.0940 - mse: 130.2490 - val_loss: 17.9405 - val_mae: 17.9180 - val_mse: 619.4266 - learning_rate: 2.5000e-04
Epoch 27/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 8.1176 - mae: 8.0848 - mse: 132.3032 - val_loss: 17.6649 - val_mae: 17.6449 - val_mse: 605.8633 - learning_rate: 2.5000e-04
Epoch 28/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.9268 - mae: 7.8950 - mse: 125.5961 - val_loss: 18.5607 - val_mae: 18.5444 - val_mse: 654.2277 - learning_rate: 2.5000e-04
Epoch 29/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.7273 - mae: 7.7018 - mse: 115.9835 - val_loss: 18.1331 - val_mae: 18.1193 - val_mse: 632.5351 - learning_rate: 1.2500e-04
Epoch 30/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.5168 - mae: 7.4928 - mse: 113.7695 - val_loss: 18.0824 - val_mae: 18.0720 - val_mse: 636.8978 - learning_rate: 1.2500e-04
Epoch 31/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 7.6478 - mae: 7.6289 - mse: 115.3085 - val_loss: 18.2545 - val_mae: 18.2479 - val_mse: 636.9982 - learning_rate: 1.2500e-04
Epoch 32/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.6268 - mae: 7.6099 - mse: 114.0483 - val_loss: 17.7506 - val_mae: 17.7476 - val_mse: 609.8743 - learning_rate: 1.2500e-04
Epoch 33/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 7.4943 - mae: 7.4801 - mse: 111.2368 - val_loss: 18.1075 - val_mae: 18.1087 - val_mse: 632.3810 - learning_rate: 1.2500e-04
Epoch 34/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 7.4949 - mae: 7.4834 - mse: 112.7689 - val_loss: 18.2192 - val_mae: 18.2215 - val_mse: 642.1110 - learning_rate: 1.2500e-04
Epoch 35/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.5537 - mae: 7.5469 - mse: 114.5834 - val_loss: 18.0537 - val_mae: 18.0597 - val_mse: 628.1075 - learning_rate: 1.2500e-04
Epoch 36/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 7.4529 - mae: 7.4481 - mse: 111.8250 - val_loss: 17.9987 - val_mae: 18.0093 - val_mse: 622.6763 - learning_rate: 1.2500e-04
Epoch 37/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.3840 - mae: 7.3806 - mse: 109.5299 - val_loss: 17.7158 - val_mae: 17.7281 - val_mse: 606.2432 - learning_rate: 1.2500e-04
Epoch 38/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.3564 - mae: 7.3578 - mse: 109.6491 - val_loss: 17.6960 - val_mae: 17.7100 - val_mse: 610.3728 - learning_rate: 1.2500e-04
Epoch 39/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 7.2371 - mae: 7.2396 - mse: 105.1146 - val_loss: 18.1035 - val_mae: 18.1199 - val_mse: 639.5345 - learning_rate: 6.2500e-05
Epoch 40/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.3044 - mae: 7.3083 - mse: 108.9286 - val_loss: 17.9253 - val_mae: 17.9443 - val_mse: 618.8025 - learning_rate: 6.2500e-05
Epoch 41/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.2476 - mae: 7.2534 - mse: 106.6650 - val_loss: 17.9725 - val_mae: 17.9926 - val_mse: 633.7178 - learning_rate: 6.2500e-05
Epoch 42/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 7.2489 - mae: 7.2560 - mse: 105.6438 - val_loss: 18.0771 - val_mae: 18.0999 - val_mse: 631.3746 - learning_rate: 6.2500e-05
Epoch 43/200
482/482 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 7.0104 - mae: 7.0192 - mse: 99.9967 - val_loss: 17.9081 - val_mae: 17.9320 - val_mse: 626.0643 - learning_rate: 6.2500e-05
Fold 5 Results -> MAE: 15.2748, RMSE: 20.8234, R²: 0.7998

=== Cross-Validation Summary ===
MAE: 15.1645, RMSE: 20.7646, R²: 0.8007

Best Fold: 4

✅ Optimized Test Results:
  MAE:  15.1485
  RMSE: 21.7624
  R²:   0.8228